### PR TITLE
chromium: Add chromimum shims

### PR DESCRIPTION
**Pull request by Neiromaster**
The regular version of Chromium already has the correct name

### CODE REVIEW

**Comment by Neiromaster** [comment]
And chrome.exe will not grind each other when installing multiple versions of the application?

**Comment by r15ch13** [comment]
`chrome.exe` will get overwritten by installing/updating another version.
But it should still be added because a user expects to have it after installing just one version of chromium.

**Comment by Neiromaster** [comment]
But if I want to install both **Google chrome**  and **Chromium** , then I will not be able to run them together from the terminal

**Comment by Ash258** [comment]
Why not??

1. Install chromium -> chrome.exe or chromimum.exe
1. Install chrome -> chrome.exe will replace chrome.exe from chromium

Reset in case of advanced usages

**Comment by Neiromaster** [comment]
Good.  If I put Chromium, and then Chrome, then everything will be fine.  But if I run "scoop update *", I won’t know what will start with chrome.exe.  A kind of Chrome Schrödinger

**Pull request merged**
