### PR TITLE
brave: Update to version 1.14.81

### LINKED ISSUE #4606: brave-browser update
brave-browser is updated with the inclusion of sync-v2.
please update the manifest so that the update is available.

### PR DESCRIPTION
**Pull request by operator-name**
~~Newer releases of brave offer zip files for win32, simplifying the installation process.~~

Closes #4606.

### CODE REVIEW

**Comment by operator-name** [comment]
Actually don't merge this yet, I have misunderstood the files. I will have to investigate where `BraveBrowserSetup.exe` finds it's files.

**Comment by operator-name** [comment]
It looks like [`chocolatey` simply runs the setup.exe.](https://chocolatey.org/packages/brave/1.14.83)

**Comment by operator-name** [comment]
The options seem to be [using the default installer](https://support.brave.com/hc/en-us/articles/360042816611-Why-isn-t-Brave-updating-automatically-on-Windows-), using [portable apps' build](https://github.com/portapps/brave-portable/releases) or another third party. Please advise.

**Review by Ash258 — CHANGES_REQUESTED** [review]
Application which are installed into other locations than SCOOP are not accepted in official buckets.

Move this PR into non-portable bucket

**Comment by operator-name** [comment]
What about using `https://github.com/portapps/brave-portable/releases/download/1.13.82-63/brave_installer-win64.exe`, or should that be under `brave-portable.json`?

**Comment by Ash258** [comment]
If you want to use random third party "portable" installer use your own bucket.

**Comment by operator-name** [comment]
Noted.

**Pull request closed without merging**
