### PR TITLE
add rufus

### PR DESCRIPTION
**Pull request by winteryoung**

### CODE REVIEW

**Comment by r15ch13** [comment]
Nice!
But it's not starting in portable mode because the shortcut doesn't have the working directory set.

**Comment by winteryoung** [comment]
It seems currently scoop doesn't support setting working directory to shortcuts. Is that right?

**Comment by winteryoung** [comment]
Or we may set the working directory to the app directory automatically?

**Comment by winteryoung** [comment]
https://github.com/lukesampson/scoop/pull/1757
Addressing this on this PR.

**Pull request merged**
