### PR TITLE
Update ToDoList version to 7.2.1

### LINKED ISSUE #1613: todolist@7.1.5.0: hash check failed
I think the latest release of ToDoList is version 7.2.1, as of January 6:

https://groups.google.com/forum/#!category-topic/abstractspoon-todolist-support/discussion-topic/PtjXKQ5o5_o

I don't think the main website for the software has been updated yet to reflect the change.

PS C:\Users\daniel> scoop install todolist
Installing 'todolist' (7.1.5.0) [64bit]
todolist_exe.zip (3.0 MB) [===================================================================================] 100%
Checking hash of todolist_exe.zip ... ERROR Hash check failed!
App:         extras/todolist
URL:         http://abstractspoon.pbwiki.com/f/todolist_exe.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    ce1946080c39061e577d1b539fb24c3c8ee88c8f32249ce78d36acd7fd064ce6
Actual:      7f0ce248d7e780ba28d96b37f3bd1a6e8407e7b4cda39dfe86f8e3d8a120d8b1

### PR DESCRIPTION
**Pull request by bifkit**
Change version number and SHA256 hash.
Fixes #1613.

### CODE REVIEW

**Comment by Ash258** [comment]
1. Fix checkver in manifest to match version from <https://www.techspot.com/downloads/5798-todolist.html>
1. Run checkver with -f parameter
1. Add `Close #1613` directive into PR description

**Comment by Ash258** [comment]
There was already new version release today (https://groups.google.com/forum/#!categories/abstractspoon-todolist-support/722), but there is no way how to get this version. No page contains it.

**Comment by Ash258** [comment]
@r15ch13 Found a way how to get correct new version:

<http://www.abstractspoon.com/todolist_update_new.txt> from their implementation: <https://www.codeproject.com/script/Articles/ViewDownloads.aspx?aid=5371>

**Comment by r15ch13** [comment]
@Ash258 https://github.com/lukesampson/scoop-extras/commit/e4c45e45ebcd90fbb29ccdf489846d20179a64b7

**Pull request merged**
