### PR TITLE
standardnotes: Simplify manifest

### PR DESCRIPTION
**Pull request by niheaven**
Maybe a standard NSIS extractor is prefered.

### CODE REVIEW

**Comment by Ash258** [comment]
There is much junk in pluginsdir (dlls needed for installer to work properly), which is not needed to have on user end after installation. That's why it's done original way. You just get only that you need (7zips with program data) without code duplication inside manifest.

**Comment by niheaven** [comment]
The two methods are equivalent except for a left "Uninstall Standard Notes.exe" that in this modified one. And one step for extraction, another for removing unused `$PLUGINSDIR` is more simpler than the original one.

What I mean above is there are many packages that use a same install script for NSIS, maybe a uniform script that shipped with scoop's `install.ps1` or `decompress.ps1` is prefered (like `innosetup`).

**Comment by rzpio** [comment]
> The two methods are equivalent except for a left "Uninstall Standard Notes.exe" that in this modified one. 

Why change the manifest when they are equivalent? 😄 

> And one step for extraction, another for removing unused $PLUGINSDIR is more simpler than the original one.

I think that's a matter of opinion. I had oriented myself to the manifest of [rambox-pro](https://github.com/lukesampson/scoop-extras/blob/master/bucket/rambox-pro.json). Basically, you're just moving the lines. I don't see any simplification in it. 😅 

The removal of the link to the license I also do not quite understand. `$baseurl` is actually a simplification. Thanks, I didn't think about the variable.

**Comment by niheaven** [comment]
That is, just two lines in `installer.script`, no `pre-install`, no `post-install`, for better readability. 😄 

> The removal of the link to the license I also do not quite understand. 

Please see manifest [help](https://github.com/lukesampson/scoop/wiki/App-Manifests#optional-properties) for license identifier usage: 

> For well-known licenses, please use the identifier found at [spdx.org/licenses](https://spdx.org/licenses/). For other licenses, use the URL of the license, if available. Otherwise, use “Freeware”, “Proprietary”, “Public Domain”, or “Shareware”, as appropriate.

So for `AGPL-3.0`, you should use only identifier and that will give a url (https://spdx.org/licenses/AGPL-3.0.html) when call `scoop info standardnotes`.

For `Uninstall xxx.exe`, it is certainly needless, and that is a shortcoming of this two line code.

Finally, while there is no UNIQUE NSIS unpacking function in scoop, the two methods of extraction are equivalent, and are just about opinion. So, what I mentioned here is a unique unpacking function is neccecary, for simplification.

**Comment by rzpio** [comment]
> So for AGPL-3.0, you should use only identifier and that will give a url (spdx.org/licenses/AGPL-3.0.html) when call scoop info standardnotes.

Ah, okay, thank you. 😄 

> My key point here is a unique unpacking function is neccecary, for simplification.

I agree. The process is always the same and the manifests are redundant.

**Comment by niheaven** [comment]
Waiting for NSIS common installation.

**Pull request closed without merging**
