### PR TITLE
Update vscode.json

### PR DESCRIPTION
**Pull request by lkrystynek**
Changed "Visual Studio Code" shortcut to "code" - vscode now can be launched from cmd or powershell through "code" command

### CODE REVIEW

**Comment by r15ch13** [comment]
This should already work because of the [`code.cmd` shim](https://github.com/lkrystynek/scoop-extras/blob/e7811387c884a110aa466ec75103cd9e71d41b9f/vscode.json#L6-L11).

**Comment by brandon93s** [comment]
Can confirm. I use this all day without any issues.

```ps1
# open here
code .

# open there
code c:/source
```

**Comment by lkrystynek** [comment]
Hi, I had a problem to open empty instance of vscode (without "." or path).  Could you please confirm if it works with original json? Thanks

**Comment by r15ch13** [comment]
Without any path it opens the last project for me (or an empty instance if I closed the project before closing vscode)

**Pull request closed without merging**
