### PR TITLE
coppeliasim: Add version 4.0.0

### PR DESCRIPTION
**Pull request by wngfra**
Add version 4.0.0

### CODE REVIEW

**Comment by Ash258** [comment]
Why did you open new PR with same history?

**Comment by wngfra** [comment]
I found the that branch name doesn’t follow the convention. Sorry for the confusion.

**Comment by Ash258** [comment]
Branch name is irrelevant.

**Comment by wngfra** [comment]
Thanks. One more question, how to put “bin/*.exe” in the manifest json?

**Comment by Ash258** [comment]
There is no bin folder with executables.

**Comment by wngfra** [comment]
Not `coppeliasim`, for `paraview`. The `paraview.exe` is in the bin folder.
Should I make a new branch for a new install manifest?

**Comment by Ash258** [comment]
Yes.
Do not add offtopic and not relevant questions to PRs.
Open PR for paraview and then ask.

**Pull request merged**
