### PR TITLE
Fix shadowsocks pre_install script issue.

### PR DESCRIPTION
**Pull request by TheCjw**
The `pre_install` script I wrote using `out-file` to create persist config file of shadowsocks. But I made a mistake. At the `pre_install` stage, **$persist_dir** is not created yet, so `Out-File` will fail to create `gui-config.json`, like this: 

```txt
Create empty config file for shadowsocks
out-file : Could not find a part of the path 'C:\Users\xxx\scoop\persist\shadowsocks\gui-config.json'.
At line:4 char:16
+         "{}" | out-file -en oem "$persist_dir\gui-config.json"
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

Now I changed `Out-File` to `New-Item`, It will force create `$persist_dir` when it's not existed.

```json
    "pre_install": "
    if (!(Test-Path \"$persist_dir\\gui-config.json\")) {
        Write-Host -ForegroundColor Red \"Create empty config file for shadowsocks\"
        New-Item -Force -Path \"$persist_dir\\gui-config.json\" -ItemType file -Value \"{}\" | Out-Null
    }",
```

### CODE REVIEW

**Comment by r15ch13** [comment]
Hey @rasa can you please usw the Squash merge feature? This keeps the commit history a bit more clean :wink: :smile:

**Comment by rasa** [comment]
I have been in the github GUI. It appears there's just a single commit. Where's the glitch?

**Comment by r15ch13** [comment]
On the website it's possible to select between merge, squash and rebase. Isn't that possible in the GitHub app? :open_mouth:

**Comment by rasa** [comment]
Oh sorry, I meant using github.com itself. It’s second option is “squash and merge” which I’ve been using, based on your prior (to today) feedback.

**Comment by r15ch13** [comment]
Okay didn't see that you used it. Sorry my bad. :yum: @TheCjw sorry for being off topic :grinning:

**Pull request merged**
