### PR TITLE
Add ssh-agent-wsl version 2.2

### PR DESCRIPTION
**Pull request by JanPokorny**
Hello, I am new to scoop, so I would appreciate if someone could check this manifest.

- Is the auto-update part correct?
- Is there a way to make the notes more user-friendly, eg. by a script echoing the correct path instead of the hardcoded ones?

### CODE REVIEW

**Comment by Ash258** [comment]
For notes.

Cannot really test because I do not want to install WSL, but if wsl inherit user environment variables, then you could use something like this: `eval $($SCOOP/apps/ssh-agent-wsl/current/ssh-agent-wsl -r)` or `eval $($SCOOP_GLOBAL/..... -r)`

**Comment by JanPokorny** [comment]
@Ash258 Env isn't shared to WSL, you have to explicitly enable it case-by-case, which is more work for the user. Besides, it looks like those variables aren't even set on my machine -- `Get-ChildItem env:` doesn't list them.

Can post-install script echo stuff? That would be nice, as then `wslpath -a '...path'` could be used to transform the path.

**Comment by Ash258** [comment]
You could do everything you want inside pre|post_install blocks.

**Comment by JanPokorny** [comment]
@Ash258 I think it's ready to be merged now.

**Comment by JanPokorny** [comment]
What should I do to help this get merged?

**Pull request merged**
