### PR TITLE
Add blisk

### PR DESCRIPTION
**Pull request by Ash258**

### CODE REVIEW

**Comment by Ash258** [comment]
Sorry for spam of PRs 😂 Cleaning up my personal bucket in favor of greater good. Adding / tweaking manfiests, which could satisfy more users.

**Comment by r15ch13** [comment]
Wow, that thing looks interesting! Thanks 😁

**Comment by brandon93s** [comment]
@Ash258 - The download link is broken for Blisk. Mind taking a look?

**Comment by Ash258** [comment]
No it is not. https://blisk.io/questions/install-blisk-browser-offline

```
Manifest: https://bliskcloudstorage.blob.core.windows.net/win-installers/BliskInstaller_10.1.262.144.exe#/cosi.7z
FaQ URL : https://bliskcloudstorage.blob.core.windows.net/win-installers/BliskInstaller_10.1.262.114.exe
```

**Comment by Ash258** [comment]
curl

**Comment by brandon93s** [comment]
@Ash258 - https://github.com/lukesampson/scoop-extras/commit/99e7617ff17406937cc404640def92d504c5ece8

**Comment by Ash258** [comment]
Few days ago it was workinng. https://ci.appveyor.com/project/Ash258/scoop-ash258/builds/20062921#L206 

They have to change something

**Comment by brandon93s** [comment]
It looks like they just haven't published the offline installer for the latest version quite yet, but the autoupdate ran.

**Comment by Ash258** [comment]
Version 144 was OK in day of PR and my [CI check](https://ci.appveyor.com/project/Ash258/scoop-ash258/builds/20062921#L206)

**Comment by Ash258** [comment]
99e7617ff17406937cc404640def92d504c5ece8 is pretty temporary solution (since latest version on page is 144) until i get answer from support.

**Comment by Ash258** [comment]
> This problem happens because we have an issue with the versioning. It will be fixed with the next release (soon). Thank you! -- Best regards, Blisk team

**Pull request merged**
