### PR TITLE
musicbee: Add autoupdate

### PR DESCRIPTION
**Pull request by rasa**
Installed locally fine.

### CODE REVIEW

**Comment by linsui** [comment]
Please add descriptioin.

**Comment by rasa** [comment]
I added
```
The ultimate music player to easily manage, find, and play music, podcasts, web radio stations, etc
```
per https://getmusicbee.com/

**Comment by Ash258** [comment]
Installation is not needed
image

**Comment by Ash258** [comment]
<details>
<summary>Fixed manifest</summary>

```json
{
    "version": "3.2.6902",
    "description": "The ultimate music player to easily manage, find, and play music, podcasts, web radio stations, etc",
    "license": "GPL-2.0-or-later",
    "homepage": "https://getmusicbee.com/",
    "notes": "Currently it's not possible to make Plugins and Skins persistent",
    "url": "https://www.mediafire.com/file/nl8iqge26fjt1cu/MusicBeePortable_3_2_Update3.zip/file#/dl.zip",
    "hash": "fe4875f540c3e066e8c12c82696da71b940bfa8d88419bbb6f888f589b15a900",
    "installer": {
        "script": "Get-ChildItem \"$dir\" 'MusicBeePortable*.exe' | Select-Object -First 1 -ExpandProperty Fullname | Expand-7zipArchive -DestinationPath \"$dir\" -Removal"
    },
    "bin": "MusicBee.exe",
    "shortcuts": [
        [
            "MusicBee.exe",
            "MusicBee"
        ]
    ],
    "persist": [
        "Library",
        "AppData"
    ],
    "checkver": {
        "url": "https://getmusicbee.com/downloads/",
        "regex": "(?sm)MusicBee\\s*([\\d.]+)<.*https://www\\.mediafire\\.com/file/(?<random>[^/]+)/MusicBeePortable_(?<majorminor>[^.]+)\\."
    },
    "autoupdate": {
        "url": "https://www.mediafire.com/file/$matchRandom/MusicBeePortable_$matchMajorminor.zip/file#/dl.zip"
    }
}
```

</details>

**Comment by rasa** [comment]
Non-installer version installed and runs fine locally.

**Pull request merged**
