### PR TITLE
nettraffic: Update to version 1.66.1

### PR DESCRIPTION
**Pull request by mark05e**
- Closes https://github.com/lukesampson/scoop-extras/issues/4016
- Add checkver

### CODE REVIEW

**Comment by Ash258** [comment]
Do you think it is good idea to download and extract HTML page?? Both aria2 and native download should lead to webpage instead of file.

Why do you not test installation, update and installation before posting PR?

**Comment by mark05e** [comment]
> Do you think it is good idea to download and extract HTML page?? Both aria2 and native download should lead to webpage instead of file.

I was using [NaturalDocs](https://github.com/lukesampson/scoop-extras/blob/ba6563850a2b8ba5aa7101429a809ed534e32841/bucket/natural-docs.json#L11) as reference when I did this.

**Comment by mark05e** [comment]
When I try to download from the download location using scoop, I do not get the correct file.

https://files03.tchspt.com/temp/NetTraffic1.66.1.zip

```
NetTraffic1.66.1.zip (65.2 KB) [==============================================================================] 100%
Checking hash of NetTraffic1.66.1.zip ... ERROR Hash check failed!
App:         nettraffic
URL:         https://files03.tchspt.com/temp/NetTraffic1.66.1.zip
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    dda5a1e6c25750be078d851d09613c17b7f735078625ad10302edf072817ee65
Actual:      49fa44ee8a54e1d36244f9289da81fa733fba796243ba9c54f10238f1b2f567c

Please try again or create a new issue by using the following link and paste your console output:
```

**Comment by Ash258** [comment]
That is exactly what I told you https://github.com/lukesampson/scoop-extras/pull/4198#issuecomment-636981464 ...

It download HTML page.

**Comment by mark05e** [comment]
Sorry I thought you were referring to `checkver` section.

**Comment by mark05e** [comment]
adding reference https://github.com/lukesampson/scoop/issues/2634.

Looks like some manipulation needs to be done for the download process.

**Pull request closed without merging**
