### PR TITLE
sagemath-installer: fix forwarding args from shim

### PR DESCRIPTION
**Pull request by JanPokorny**
This is a little hacky way to pass arguments to sage. It grabs the arguments the shim passes to bash.exe, cuts out the user-specified part, and then passes it to sage executable.

I also propose removing the shim for `bash.exe` (which I have no idea why is exposed in the first place) and the other two shims, as they are not needed now. But they might need to be kept for backwards compatibility?

(Also, if we decide to make backwards incompatible changes, it would be nice to rename the shim from `sagemath` to `sage` (for platform consistency) and the package from `sagemath-installer` to just `sagemath` (because the `-installer` part has no meaning).)

### CODE REVIEW

**Comment by JanPokorny** [comment]
This does not seem to respect current working directory, marking WIP until I find out how to fix

**Comment by JanPokorny** [comment]
This is now ready, with full argument and Windows path support. (As said previously, this makes other shims obsolete, but I don't know what is Scoop's deprecation policy.)

**Comment by Ash258** [comment]
I really do not understand what this should do.

Why do you create ugly and unmaintable way how to deal with it? Just create wrapper powershell script in `installer.script` with all the argument handling and then shim this wrapper.

**Comment by JanPokorny** [comment]
@Ash258 I considered this option, but ultimately it will just be the same code, echoed into new ps1 file. I know that the code looks ugly, but cygwin is just shitty at Windows interop and Sage has to be run through cygwin bash (and it furthermore has to be login shell). Also all paths need to be translated to the UNIX format by cygpath.

I can remake it as an installer script that echoes it into ps1 file and then shims that, if you think that's the better option. That would at least allow me to define variables and thus make the line more readable. But again, it would be powershell in string in powershell in JSON...

**Comment by Ash258** [comment]
It will be simple pre_install with Array of single quoted strings.


```ps1
"pre_install": [
    "$CONT = @(",
    "    '#SOme hadnling of parameters'",
    "    '....'",
    "    '$login = ....'",
    "    '& \"$PSScriptRoot\\..\\bin\\bash.exe\" --login ....'",
    ")",
    "Set-Content sagemath.ps1 $CONT -Encoding ASCII",
]
```

**Comment by JanPokorny** [comment]
@Ash258 OK, I'll try that. Hope I won't get lost in the 6 layers of escaping... 😄

**Comment by JanPokorny** [comment]
@Ash258 Could please look at #3003 first? It's a pretty simple path fix for the same manifest. It also touches installation scripts, so I don't want to create conflicts.

**Comment by JanPokorny** [comment]
@Ash258 What about now?

BTW, what's your opinion on renaming `sagemath-installer` to simply `sagemath`? (The part `-installer` is nonsensical in the first place.) Does Scoop has some non-havoc-wreaking way of renaming packages, or is it too much hassle?

**Comment by Ash258** [comment]
Synchronize with master. There are no changes from #3003

**Comment by Ash258** [comment]
Since right now I am under metered connection I will see later with whole installation process as soon as I am able to download bigger files.

<details>
<summary>Fixed manifest with optimized checkver and autoudpate</summary>

- Also some properties sort and manifest ergonomic tweaks

```json
{
    "version": "0.5.1-8.9",
    "description": "Mathematics software system",
    "homepage": "https://www.sagemath.org",
    "license": "GPL-2.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/sagemath/sage-windows/releases/download/0.5.1-8.9/SageMath-8.9-Installer-v0.5.1.exe",
            "hash": "955f47f50052a9819b2c4aa9b75fc7bfa994eeb83e98a8df44beacb762a653cb"
        }
    },
    "innosetup": true,
    "installer": {
        "script": [
            "$CONT = @(",
            "    '$exedir = \"$PSScriptRoot\\runtime\\bin\"'",
            "    '$cwd_unix = (& \"$exedir\\cygpath.exe\" -- (Get-Location).Path)'",
            "    '$args_unix = ($args | ForEach-Object { & \"$exedir\\cygpath.exe\" -- $_ })'",
            "    '$args_unix_quoted = ($args_unix | ForEach-Object { \"''$_''\" })',",
            "    '& \"$exedir\\bash.exe\" --login -c \"cd ''$cwd_unix'' && /opt/sagemath-*/sage $args_unix_quoted\"'",
            ")",
            "Set-Content $dir\\sagemath.ps1 $CONT -Encoding ASCII",
            "@('etc\\fstab.d', 'dev\\shm', 'dev\\mqueue', 'home\\sage') | ForEach-Object {",
            "    New-Item \"$dir\\runtime\\$_\" -Force -Type Directory | Out-Null",
            "}",
            "Get-Content \"$dir\\runtime\\etc\\symlinks.lst\" | ForEach-Object {",
            "    (Get-Item \"$dir\\runtime\\$_\").Attributes = 'System'",
            "}"
        ]
    },
    "bin": [
        "sagemath.ps1",
        [
            "sagemath.ps1",
            "sage"
        ],
        [
            "sagemath.ps1",
            "sagemath-shell",
            "-sh"
        ],
        [
            "sagemath.ps1",
            "sagemath-notebook",
            "--notebook"
        ]
    ],
    "shortcuts": [
        [
            "runtime\\bin\\mintty.exe",
            "SageMath",
            "-t 'SageMath' /bin/bash --login -c '/opt/sagemath-*/sage'",
            "sagemath.ico"
        ],
        [
            "runtime\\bin\\mintty.exe",
            "SageMath Shell",
            "-t 'SageMath Shell' /bin/bash --login -c '/opt/sagemath-*/sage -sh'",
            "sagemath.ico"
        ],
        [
            "runtime\\bin\\mintty.exe",
            "SageMath Notebook",
            "-t \"SageMath Notebook\" /bin/bash --login -c \"/opt/sagemath-*/sage --notebook\"",
            "sagemath.ico"
        ]
    ],
    "checkver": {
        "github": "https://github.com/sagemath/sage-windows",
        "regex": "tag/([\\d-.]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/sagemath/sage-windows/releases/download/$version/SageMath-$preReleaseVersion-Installer-v$matchHead.exe"
            }
        }
    }
}
```

</details>

**Pull request merged**
