### PR TITLE
todolist: Add app manifest

### PR DESCRIPTION
**Pull request by moosad**
#1433

### CODE REVIEW

**Comment by moosad** [comment]
I would need some help with checkver. On the homepage there are only major and minor versions. The only place where I could find the full version number is the [forum](https://groups.google.com/forum/#!forum/abstractspoon-todolist-support), but I could use multi-line regex only.

**Comment by Ash258** [comment]
You can't use forum, because Google forums are heavily generated after execution.

See resulted file of `curl https://groups.google.com/forum/#!forum/abstractspoon-todolist-support -o cosi.html`

You will only see something like: `You need to enable javascript to load this page` message in bunch of javascript ugly code.

**Comment by Ash258** [comment]
Since it's single file URL which does not change with version, you could make it nightly.

**Comment by moosad** [comment]
I found two up-to-date sites, [filehippo](https://filehippo.com/download_todolist) and [techworld](https://www.techworld.com/download/office-business/todolist-7150-3249271/) where I can check the version, so I implemented checkver. Also gave the same autoupdate url as actual url just to compute the latest hash.
I hope it's okay now. 🙂

**Pull request merged**
