### PR TITLE
lingoes: Add version 2.9.2

### PR DESCRIPTION
**Pull request by snowman**

### CODE REVIEW

**Review by Ash258 — CHANGES_REQUESTED** [review]
- Remove checkver and autoupdate
- Why do you prefer installer over zip?

image

**Comment by snowman** [comment]
There is only `one` version of the portable zip, but the installer has both two `x32` and `x64` versions.

**Comment by Ash258** [comment]
/verify Download do not work, causing weird redirect

A

B

**Comment by snowman** [comment]
That's not I could help, so should close this pull request?

**Pull request closed without merging**
