### PR TITLE
Add winpython manifest

### PR DESCRIPTION
**Pull request by benplm**
Not really sure if this belongs here, but since some people (me included) had trouble with the Python installer not being always handled properly by Scoop and/or not installing some .dll files and libraries even when installed manually (https://github.com/lukesampson/scoop/issues/504, https://github.com/lukesampson/scoop/issues/324, https://github.com/lukesampson/scoop/issues/2290, https://github.com/lukesampson/scoop/issues/856), I thought a 100% portable and working Python distribution could be useful for many.

I made it so that only Python is extracted, while the GUI tool developed by winpython is not, so no 3rd party software will be extracted (no launchers, no configuration tools other than Scoop).

I hope you'll find this useful.

### CODE REVIEW

**Comment by r15ch13** [comment]
Nice 👍
Also made some adjustments :smile:

**Comment by rasa** [comment]
Stoked that this has been added, but shouldn’t it live in the main bucket with python?

**Comment by r15ch13** [comment]
@benplm can you make a PR for this manifest on the main repo to move it? 😁

**Comment by benplm** [comment]
@r15ch13 sure, I'll do asap. I thought it would have been redundant there, that's why I did a PR here. 😅

**Comment by rasa** [comment]
Not redundant at all. If anything, it's more a CLI than the standard python package.

**Pull request merged**
