### PR TITLE
fix: foobar2000-encoders, update checkver re and encoders folders 

### PR DESCRIPTION
**Pull request by ShuguangSun**
update foobar2000-encoders version, chan checkver's re; fix the Copy-item issue, and make the folder of encoders

### CODE REVIEW

**Comment by Ash258** [comment]
Why to keep installer when you added extract_to property and changed exe to 7z.

**Comment by ShuguangSun** [comment]
If it is not changed from exe to 7z, it can't installed in my machine. Don't know why.

**Comment by Ash258** [comment]
Then just delete `installer` property if it could be just extracted

**Comment by ShuguangSun** [comment]
Thanks to point it out.

The rational I change exe to 7z is because the exe installer require administrator rights.
Windows 10.

**Pull request closed without merging**
