### PR TITLE
Flutter: 脚本变更

### PR DESCRIPTION
**Pull request by fanlide**
#2924 #2439

### CODE REVIEW

**Comment by fanlide** [comment]
Version number is not satisfied `^[\w\.\-_]+$`, resulting in verification does not pass, please fix under. 

image

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop-extras/pull/2770 https://github.com/lukesampson/scoop/pull/3613

**Comment by fanlide** [comment]
@linsui I gave up regex, and used jsonpath. I believe my way is better.

**Comment by linsui** [comment]
I agree, see https://github.com/ScoopInstaller/Main/pull/366 😂

**Comment by fanlide** [comment]
I don't think adopt8 is necessary. Other jdk can still. I installed zulu8,. I don't want to install adopt8.

**Pull request closed without merging**
