### PR TITLE
tableplus: Update to version 3.10.4.142

### PR DESCRIPTION
**Pull request by OranShuster**

### CODE REVIEW

**Comment by OranShuster** [comment]
@Ash258 does `package-fix-needed`  mean there is an issue with my change? since you didn't comment anything i thought it was ok

**Comment by Ash258** [comment]
I will comment when I have time for fixing the clear problem with autoupdate and version checking.

**Comment by OranShuster** [comment]
`checkver` is working fine
change `autoupdate` to use `$matchHead` and now that works also

**Pull request merged**
