### PR TITLE
Add and fix some au.hash

### PR DESCRIPTION
**Pull request by linsui**

### CODE REVIEW

**Comment by Ash258** [comment]
Really?? Again this huge PR? 

You know how time consuming is to reveiew this and then each merging from master after update? Completely not worth and mess.

Learn how to user `hub` for posting PRs from command line and post PR for each manfiest.

**Comment by linsui** [comment]
I'll have a try. By the way, could chocolatey be used to get hash?

**Comment by niheaven** [comment]
Of course you can, see https://github.com/lukesampson/scoop/pull/3249 for some attemp. But make sure the files are unique if you use Choco's checksum with something downloaded elsewhere.

**Comment by linsui** [comment]
@niheaven I mean when scoop update a manifest maybe choco haven't update its. Dose it make sense to get hash from choco? Or we should also checkver from choco?

**Comment by niheaven** [comment]
Use checkver from Choco, too. See ScriptCs for example. If the PR is merged, using `choco` in checkver and au are more preferred.

**Pull request closed without merging**
