### PR TITLE
libreoffice-fresh: Fix installation

### LINKED ISSUE #5208: LibreOffice Fresh 'Could not find 'LibreOffice'! (error 16)'
```
➤ scoop install libreoffice-fresh
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'libreoffice-fresh' (7.0.3.1) [64bit]
Loading LibreOffice_7.0.3.1_Win_x64.msi from cache.
Checking hash of LibreOffice_7.0.3.1_Win_x64.msi ... ok.
Extracting LibreOffice_7.0.3.1_Win_x64.msi ... Could not find 'LibreOffice'! (error 16)
At C:\Users\sedlund\scoop\apps\scoop\current\lib\core.ps1:510 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'LibreOffice'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'LibreOffice'! (error 16)

```

### LINKED ISSUE #5327: Can't install Libreoffice 7.0.4.2
屏幕截图 2020-12-18 135710

I've tried several times but still the same result.

### PR DESCRIPTION
**Pull request by ustsv**
- Closes #5327
- Closes #5208

### CODE REVIEW

**Review by Ash258 — CHANGES_REQUESTED** [review]
image

**Review by StarsbySea — COMMENTED** [review]
After applying this patch, I was able to install LibreOffice properly. exactly the opposite of Ash258's result.

**Comment by Ash258** [comment]
It works only with native msiexec, not with lessmsi. Until this is fixed it will not be merged...

**Review by lugark — APPROVED** [review]
fix works for me :)

**Review by SharakPL — CHANGES_REQUESTED** [review]
Old urls don't work anymore. Here's the new ones (hash is the same):
```
        "64bit": {
            "url": "https://download.documentfoundation.org/libreoffice/stable/7.0.4/win/x86_64/LibreOffice_7.0.4_Win_x64.msi",
            "hash": "37a36b570a599b9c1e377b7c709155dd566a5eb1e8e857ca139b824d3a12e55b"
        },
        "32bit": {
            "url": "https://download.documentfoundation.org/libreoffice/stable/7.0.4/win/x86/LibreOffice_7.0.4_Win_x86.msi",
            "hash": "a19084d17b2170e08319651846c73fff9f103f5e69aa35f8d06f34c55f2cde32"
        }
```

**Comment by SharakPL** [comment]
> 
> 
> There are two different shell windows with different setup in the screenshot...
> 
> It works only with native msiexec, not with lessmsi. Until this is fixed it will not be merged...

@Ash258 What exactly is to fix here other than invalid urls? What's the purpose of lessmsi? Does it require `extract_dir`?

**Comment by SharakPL** [comment]
@Ash258 sadly it didn't fix the installation 😞 still generates an error, only now it installs `lessmsi`. What for??? 7.0.3 installed with no problems and it didn't need any additional packages like lessmsi.

``` ps
scoop install libreoffice-fresh
Installing 'lessmsi' (1.8.1) [64bit]
lessmsi-v1.8.1.zip (496,7 KB) [===============================================================================] 100%
Checking hash of lessmsi-v1.8.1.zip ... ok.
Extracting lessmsi-v1.8.1.zip ... done.
Linking ~\scoop\apps\lessmsi\current => ~\scoop\apps\lessmsi\1.8.1
Creating shim for 'lessmsi'.
Creating shortcut for Less MSIérables (lessmsi-gui.exe)
'lessmsi' (1.8.1) was installed successfully!
Installing 'libreoffice-fresh' (7.1.0.3) [64bit]
LibreOffice_7.1.0.3_Win_x64.msi (313,2 MB) [==================================================================] 100%
Checking hash of LibreOffice_7.1.0.3_Win_x64.msi ... ok.
Running pre-install script...
Could not find 'LibreOffice'! (error 16)
At C:\Users\Tomek\scoop\apps\scoop\current\lib\core.ps1:510 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'LibreOffice'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'LibreOffice'! (error 16)
```

**Comment by b-reich** [comment]
@Ash258 still the same error
grafik

**Pull request closed without merging**
