### PR TITLE
playnite: Persist additional folders

### PR DESCRIPTION
**Pull request by Skyline404**
Fixed ?

### CODE REVIEW

**Comment by Ash258** [comment]
Do you really think it is necessary to open new PR without closing the first one??

**Comment by Skyline404** [comment]
> 
> 
> Do you really think it is necessary to open new PR without closing the first one??

Sry didnt know how to close pr :)

**Review by Ash258 — COMMENTED** [review]
How do you update Extension from UI?

**Comment by Skyline404** [comment]
> 
> 
> How do you update Extension from UI?

Double click on pext extension

**Review by Ash258 — CHANGES_REQUESTED** [review]
A

There is no update feature of the extensions inside Playnite UI, which effectively prevents it from being persisted as there is no merging support for the persisted folders. So as soon as developers pack new version of the native extensions it will not be updated as it will use old versions. Which will lead to the misbehavior of application and user have to man manually struggle with tracing down the changed extensions and fixing it. Which is unacceptable.

**Comment by Skyline404** [comment]
> 
> 
> There is no update feature of the extensions inside Playnite UI, which effectively prevents it from being persisted as there is no merging support for the persisted folders. So as soon as developers pack new version of the native extensions it will not be updated as it will use old versions. Which will lead to the misbehavior of application and user have to man manually struggle with tracing down the changed extensions and fixing it. Which is unacceptable.
> 
> A

I see, default installer persists custom extensions on update somehow

**Pull request closed without merging**
