### PR TITLE
sourcetree: Update to version 3.1.3

### PR DESCRIPTION
**Pull request by biehlermi**

### CODE REVIEW

**Comment by linsui** [comment]
You need to fix the versioin and checkver, too. Or it will be change back. I don't know why the release file haven't been updated, maybe it will be updated later? 

```json
{
    "version": "3.1.3",
    "homepage": "https://www.sourcetreeapp.com/",
    "description": "Simplicity and power in a beautiful Git GUI.",
    "url": "https://www.sourcetreeapp.com/update/windows/ga/SourceTree-3.1.3-full.nupkg",
    "hash": "08d3133c2a7929c40b78ceff9f91ff0d35c2ea0fc68d3b39cc735cfab888ecce",
    "extract_dir": "lib\\net45",
    "bin": "sourcetree.exe",
    "shortcuts": [
        [
            "sourcetree.exe",
            "Atlassian SourceTree"
        ]
    ],
    "checkver": "SourceTreeSetup-([\\d.]+).exe",
    "autoupdate": {
        "url": "https://www.sourcetreeapp.com/update/windows/ga/SourceTree-$version-full.nupkg"
    }
}
```

**Comment by biehlermi** [comment]
> You need to fix the versioin and checkver, too. Or it will be change back. I don't know why the release file haven't been updated, maybe it will be updated later?

Thanks for your feedback. I've just changed the version now.

**Comment by linsui** [comment]
Please fix `checkver` and `autoupdate` , too. See https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate

**Comment by biehlermi** [comment]
Did it! Thank you. :)

**Comment by Ash258** [comment]
Now when you change autoupdate urls to be same as checker `https://product-downloads.atlassian.com/software/sourcetree/windows/ga/SourceTree-$version-full.nupkg` and run `.\bin\checkver.ps1 SourceTree -f` It should automatically get correct hash for current version

**Comment by Ash258** [comment]
So this is final manifest:

<details>
<summary>Fixed manifest</summary>

```json
{
    "version": "3.1.3",
    "description": "Simplicity and power in a beautiful Git GUI.",
    "homepage": "https://www.sourcetreeapp.com/",
    "license": {
        "identifier": "Proprietary",
        "url": "https://www.atlassian.com/legal/software-license-agreement"
    },
    "url": "https://product-downloads.atlassian.com/software/sourcetree/windows/ga/SourceTree-3.1.3-full.nupkg",
    "hash": "sha1:3687b9f885d87c748a164e58124e732567857272",
    "extract_dir": "lib\\net45",
    "bin": "sourcetree.exe",
    "shortcuts": [
        [
            "sourcetree.exe",
            "Atlassian SourceTree"
        ]
    ],
    "checkver": {
        "url": "https://product-downloads.atlassian.com/software/sourcetree/windows/ga/RELEASES",
        "regex": "SourceTree-([\\d.]+)-full.nupkg",
        "reverse": true
    },
    "autoupdate": {
        "url": "https://product-downloads.atlassian.com/software/sourcetree/windows/ga/SourceTree-$version-full.nupkg",
        "hash": {
            "url": "$baseurl/RELEASES"
        }
    }
}
```

</details>

**Comment by biehlermi** [comment]
Fixed it! :)

**Pull request merged**
