### PR TITLE
Fix pwsafe installation

### PR DESCRIPTION
**Pull request by teppos**

### CODE REVIEW

**Comment by r15ch13** [comment]
Thanks.
What's the reason for changing it to the installer? They still provide the zip files
https://github.com/pwsafe/pwsafe/releases/latest

**Comment by teppos** [comment]
It extracted the zip to a subdirectory (pwsafe-3.47.1-bin) and failed to install the shortcuts to startmenu-shortcuts

**Comment by r15ch13** [comment]
The `extract_dir` property is avaialable for this.

Add this to 64bit
`"extract_dir": "pwsafe64-3.47.1-bin"`
This to 32bit
`"extract_dir": "pwsafe-3.47.1-bin"`

And these to the `autoupdate` property:
`"extract_dir": "pwsafe64-$version-bin"`
`"extract_dir": "pwsafe-$version-bin"`

**Comment by teppos** [comment]
Ok will try, thanks

**Pull request merged**
