### PR TITLE
Chromes: Add hash extraction and all chrome versions

### LINKED ISSUE #1984: [Request] Chrome Beta, Dev, and Canary
I saw that Chrome was supported in https://github.com/lukesampson/scoop-extras/pull/1931.

Google Chrome has multiple channels : https://www.chromium.org/getting-involved/dev-channel

I'd like to request adding the channels Beta, Dev, and Canary.

### PR DESCRIPTION
**Pull request by Ash258**
- Closes #1984 

- Use direct google url.
- Add hash extraction

Thx @h404bi for website ❤😍

This should  be merged when lukesampson/scoop#3458 is in master

TODO: 

- [ ] Simplify installer.script with `Expand-7zipArchive \"$dir\\chrome.7z\" -ExtractDir 'Chrome-bin' -Removal` (When lukesampson/scoop#3466 is in master)

### CODE REVIEW

**Comment by h404bi** [comment]
I strongly recommend to use `googlechrome` instead of `chrome` as the manifest name. People can search `googlechrome` or `chrome` to find the app when they are named `googlechrome`, while only `chrome` if they are named `chrome`. `Google Chrome` is a brand, `Chrome` is not, it's just a shortname.

**Comment by Ash258** [comment]
I really do not mind naming. If `googlechrome` is more suitable for more users i will `git mv` them to `googlechrome` prefix

**Comment by Ash258** [comment]
@scoopinstaller Thoughts on naming?

**Note: Not sure if `@scoopinstaller` will trigger notification for all members 🤔

**Comment by Ash258** [comment]
Canary sometimes have different versions for each architecture

a

**Comment by ssfjhh** [comment]
#3458 has been merged, why this PR hasn't been merged so far?

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop-extras/pull/2144#issuecomment-492186117

**Comment by Ash258** [comment]
Thoughts / Votes about renaming? @r15ch13, @niheaven, @h404bi, @rasa, @brandon93s, @se35710, @NatoBoram

`chrome` -> `googlechrome`
`chrome-beta` -> `googlechrome-beta`
`chrome-canary` -> `googlechrome-canary`
`chrome-dev` -> `googlechrome-dev`

🚀 Old
👀 New

**Comment by NatoBoram** [comment]
I don't mind the renaming. If installing fails, I'd typically look up on the GitHub repo and see why. It's an easy fix for downstream, and the error message is explicit enough.

On the topic of renaming, I'd rename [`pwsh`](https://github.com/lukesampson/scoop-extras/issues/2221) 🙂

**Comment by rasa** [comment]
+1 to rename, as chocolatey uses `goog;echrome`

**Comment by Ash258** [comment]
Everything ready to merge

**Comment by rasa** [comment]
Is this GTG?

**Comment by Ash258** [comment]
From 15th of May

**Comment by linsui** [comment]
> - [ ] TODO:
>
> Simplify installer.script with `Expand-7zipArchive \"$dir\\chrome.7z\" -ExtractDir 'Chrome-bin' -Removal` (When lukesampson/scoop#3466 is in master)

When will this be done?

**Comment by Ash258** [comment]
in next PR

**Pull request merged**
