### PR TITLE
dropit: add a new app

### PR DESCRIPTION
**Pull request by FloatingShuYin**

### CODE REVIEW

**Comment by linsui** [comment]
Persist profiles and settings.ini. Scoop can extract hash from sourceforge automatically. homepage is default checkver.url.

```
{
    "version": "8.5.1",
    "homepage": "http://www.dropitproject.com/",
    "description": "Personal assistant to automatically manage your files",
    "license": "GPL-3.0-only",
    "url": "https://download.sourceforge.net/projects/dropit/files/DropIt/v8.5.1/DropIt_v8.5.1_Portable.zip",
    "hash": "sha1:882c765830b307d8b2d90b4411e061d39d79a28c",
    "pre_install": "if (!(Test-Path \"$persist_dir\\settings.ini\")) { New-Item \"$dir\\settings.ini\" -Force | Out-Null }",
    "extract_dir": "DropIt_v8.5.1_Portable",
    "bin": "DropIt.exe",
    "shortcuts": [
        [
            "DropIt.exe",
            "DropIt"
        ]
    ],
    "persist": [
        "Profiles",
        "settings.ini"
    ],
    "checkver": "Latest Version: v([\\d.]+)",
    "autoupdate": {
        "url": "https://download.sourceforge.net/projects/dropit/files/DropIt/v$version/DropIt_v$version_Portable.zip",
        "extract_dir": "DropIt_v$version_Portable"
    }
}

```

**Comment by FloatingShuYin** [comment]
I am negligent, I have modified my commit using the code you posted.

**Comment by r15ch13** [comment]
Please run `.\bin\checkver.ps1 dropit -f` to test the auto-update and fix the formatting.

**Comment by Ash258** [comment]
With a fast static look at manifest it cannot work as download mirror of sourceforge is `downloads` not `donwload` and should not contains `files` string

This one should work:

`https://downloads.sourceforge.net/project/dropit/DropIt/v8.5.1/DropIt_v8.5.1_Portable.zip`

**Pull request closed without merging**
