### PR TITLE
blender: Update to version 2.80

### PR DESCRIPTION
**Pull request by intelligide**

### CODE REVIEW

**Comment by Jogai** [comment]
I still got an error about the blenderplayer, and I didnt have a previous version installed.

```
Download: (OK):download completed.

Checking hash of blender-2.80-windows64.zip ... ok.

Extracting blender-2.80-windows64.zip ... done.

Linking ~\scoop\apps\blender\current => ~\scoop\apps\blender\2.80

Creating shim for 'blender'.

Creating shim for 'blenderplayer'.

Can't shim 'blenderplayer.exe': File doesn't exist.

**Comment by intelligide** [comment]
The blender player doesn't exists anymore in 2.80 and later.

**Comment by Jogai** [comment]
I know, and I see it removed from the bin entries in the json. so why is scoop still trying to create a shim for it?

**Comment by Ash258** [comment]
Because this PR was not merged. Update was done automatically using Excavator and blendplayer removal is done in #2539

**Pull request closed without merging**
