### PR TITLE
 Fix some license 

### PR DESCRIPTION
**Pull request by linsui**
😄

### CODE REVIEW

**Comment by Ash258** [comment]
I really do not know why do you mix license fixing and some other fixes. 

It is complete mess to review everything in one huge PR.

**Comment by linsui** [comment]
Do I need to extract other fix into another commit?

**Comment by r15ch13** [comment]
@linsui yes, please move the other changes to another PR, to keep the history clean. :smile:

**Comment by linsui** [comment]
Ok， I'll do it later 😂

**Pull request closed without merging**
