### PR TITLE
Add Olive Editor Nightly

### PR DESCRIPTION
**Pull request by igitur**
Add Olive Editor Nightly builds.

This is my first attempt at adding a package. Please be gentle.

### CODE REVIEW

**Comment by Ash258** [comment]
Move this PR into versions or nightly bucket

**Comment by igitur** [comment]
Thanks. Where's the nightly bucket? URL?

**Comment by igitur** [comment]
@Ash258 Please help me out by what you meant. Is there an existing nightly bucket, or do you suggest that I create and host my own?

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop/blob/master/buckets.json

**Comment by igitur** [comment]
Ah, thanks, Mr Talkative ;-)

**Pull request closed without merging**
