### PR TITLE
m4a-to-mp3-converter: Add version X.89

### PR DESCRIPTION
**Pull request by digrouz**
I cannot get this one to work, can someone help me?

### CODE REVIEW

**Comment by Ash258** [comment]
<details>
<summary>Fixed manifest</summary>

```json
{
    "version": "X.89",
    "description": "M4a to MP3 converter",
    "homepage": "https://www.maniactools.com/soft/m4a-to-mp3-converter/",
    "license": "Freeware",
    "url": "https://www.maniactools.com/soft/m4a-to-mp3-converter.exe",
    "hash": "5872d19451f7f6fdd796f846e53bc9cae5a9270a71ba12ae689f40df98727c32",
    "innosetup": true,
    "shortcuts": [
        [
            "m4a_converter.exe",
            "Free M4a to MP3 Converter"
        ]
    ],
    "checkver": {
        "url": "https://www.maniactools.com/cgi-bin/version?prog=m4a-converter",
        "regex": "Free M4a to MP3 Converter\\s+([\\w]+)\\s+Build\\s+(?<build>[\\d]+)",
        "replace": "$1.${build}"
    },
    "autoupdate": {
        "url": "https://www.maniactools.com/soft/m4a-to-mp3-converter.exe"
    }
}

```

</details>

**Comment by digrouz** [comment]
How do you know it's an innosetup ?

**Comment by digrouz** [comment]
Thanks for the fix by the way :)

**Comment by Ash258** [comment]
Because it contains files, which are typical for innosetup.

**Comment by digrouz** [comment]
done

**Comment by digrouz** [comment]
Hello, is there still any issue preventing the merge of this pull request?

**Pull request merged**
