### PR TITLE
Calibre: Change URL to fosshub

### PR DESCRIPTION
**Pull request by niheaven**
FossHub is more stabler and faster than GitHub.

### CODE REVIEW

**Comment by Ash258** [comment]
Why to remove hash and checver from github? Files should be identical or not?

**Comment by niheaven** [comment]
FossHub link could use `fosshub` mode to get hash, and checkver from fosshub to avoid inconsistency of release time between github and fosshub.

**Comment by niheaven** [comment]
Files are identical from all releasing sources.

**Comment by Ash258** [comment]
Could be fosshub hash extract changed to sha1 or md5? This would distinguish fosshub hashmode at first for review. Without specifying `hash.mode`

My point is that lots of new contributors do not know about checkver and make everything manually (url, hashes, extracts,..) and when you see that there is sha1 or md5 hash inside manifest you know, that user ran checkver and you do not need to download that file and check it while review. (Same as in sourceforge). When you review sourceforge and you see sha256 hash you know, something is wrong.

**Comment by niheaven** [comment]
Yes, it could, the hash extraction regex is https://github.com/lukesampson/scoop/blob/master/lib/autoupdate.ps1#L217 (`$Matches.filename+'.*?"sha256":"([a-fA-F0-9]{64})"'`), just change it to sth. likes `"sha1":"([a-fA-F0-9]{40})"` or `"md5":"([a-fA-F0-9]{32})"`.

The hash in html is as follow:

```
{"n":"calibre-3.41.3.msi","r":"5cba8e83d0a6f00ad7fd0fb5","hash":{"md5":"ec913c8ea7527078c55a5012bf0bf49e","sha1":"08a624eaaccc17168a6545a55758e96dd17f426c","sha256":"727d57b5096ca236113af68a9b69a253af40676985ca63b2f2d1816800aaa022"},"s":false}
```

**Comment by niheaven** [comment]
If sha1 is preferred for review, I could submit a PR to change it. For daily use, the safety of sha1 and sha256 should be identical.

**Pull request merged**
