### PR TITLE
micmute: Add version 0.8.0

### PR DESCRIPTION
**Pull request by SaifAqqad**

### CODE REVIEW

**Comment by Ash258** [comment]
For what reason you did close the previous PR??

**Comment by SaifAqqad** [comment]
Because that one was for 0.7.9
This one's for 0.8.0
The startup shortcut part is no longer necessary now that it uses task scheduler

**Comment by Ash258** [comment]
And it is impossible to update the already existing PR/branch right?

**Comment by SaifAqqad** [comment]
Lol I'm sorry man
I had already made another branch and pushed the new file onto it, because I thought the old pr would have already been merged but afterwards I checked and it wasn't so I closed it and made a new pr from the other branch

**Review by Ash258 — APPROVED** [review]

**Pull request merged**
