### PR TITLE
teamspeak3: Fix autoupdate

### PR DESCRIPTION
**Pull request by linsui**
Close https://github.com/lukesampson/scoop-extras/issues/2750

### CODE REVIEW

**Comment by r15ch13** [comment]
Update service fixed it already. https://github.com/lukesampson/scoop-extras/commit/ec9569e6156576a386b53194c0a0130ccd8ec699

**Comment by Ash258** [comment]
@r15ch13 No. There is still url `https://files.teamspeak-services.com/releases/client/3.3.0/TeamSpeak3-Client-win64-3.3.2.exe#/cosi.7z`, which shoul be `https://files.teamspeak-services.com/releases/client/3.3.2/TeamSpeak3-Client-win64-3.3.2.exe#/cosi.7z`

```diff
-https://files.teamspeak-services.com/releases/client/3.3.0/TeamSpeak3-Client-win64-3.3.2.exe#/cosi.7z
+https://files.teamspeak-services.com/releases/client/3.3.2/TeamSpeak3-Client-win64-3.3.2.exe#/cosi.7z
```

**Comment by r15ch13** [comment]
Oh!

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop-extras/commit/f76470d418fe675b51991c6afbb1c5f9373e9a14

**Pull request closed without merging**
