### PR TITLE
added dotpeek

### PR DESCRIPTION
**Pull request by MichielVanwelsenaere**

### CODE REVIEW

**Comment by MichielVanwelsenaere** [comment]
@Ash258 , any idea why this is failing?

**Comment by Ash258** [comment]
https://ci.appveyor.com/project/lukesampson/scoop-extras/builds/21400801/job/lp7y54r1jnvl4hhm#L73

There is no new line at the end of file.

**Comment by r15ch13** [comment]
I would recommend using the jetbrains-toolbox

**Comment by MichielVanwelsenaere** [comment]
@r15ch13 , the toolbox adds some stuff in the windows toolbar and I don't see how it can automate installing dotpeek from there? My intent here is to get only dotpeek

**Comment by MichielVanwelsenaere** [comment]
any idea when this can be merged?

**Pull request merged**
