### PR TITLE
Add RedPen

### PR DESCRIPTION
**Pull request by blyoa**
I added [RedPen](http://redpen.cc/), which was a proofreading tool for writers or programmers.

### CODE REVIEW

**Comment by blyoa** [comment]
Thank you for the quick review. I updated the PR.
Yes, RedPen is only a command line utility.

**Comment by Ash258** [comment]
Then move this PR into [main bucket](https://github.com/ScoopInstaller/Main/)

**Comment by Ash258** [comment]
I almost forget. Add suggest for java please.

```json
"suggest":{
     "Java": [
          "oraclejdk",
          "some JRE from java bucket"
     ]
}
```

**Comment by blyoa** [comment]
I added the additional key and I sent [a new PR](https://github.com/ScoopInstaller/Main/pull/70) to main bucket. Thank you for the review.

**Pull request closed without merging**
