### PR TITLE
Fix URL in unlocker

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by rasa** [comment]
But see https://github.com/lukesampson/scoop-extras/issues/465 before you merge.

**Comment by r15ch13** [comment]
I put in my [keybase public folder](https://keybase.pub/r15ch13/unlocker/) including checksums and all. 

Use this as the download URL: https://r15ch13.keybase.pub/unlocker/unlocker1.9.0-portable.zip

**Comment by rasa** [comment]
Done. I'll close #465 .

**Comment by r15ch13** [comment]
Why did you merge the upstream master into the PR? 😕 
You don't need to do that 😄

**Comment by rasa** [comment]
Yeah, sorry 'bout those. I forget to add `--no-commit` to my upstream merges.

**Pull request merged**
