### PR TITLE
Some useful graphics editors / tools

### PR DESCRIPTION
**Pull request by se35710**

### CODE REVIEW

**Comment by lukesampson** [comment]
Looks good. Why is Inkscape 32 bit in a separate manifest though?

**Comment by se35710** [comment]
The download url is unfortunately different depending on architecture, so I created a separate manifest so that autoupdate would work.

**Comment by lukesampson** [comment]
@r15ch13 Is it possible to have a different autoupdate URL based on architecture?

**Comment by r15ch13** [comment]
That's a tricky one. Currently `checkver` doesn't support architectures.

**Pull request merged**
