### PR TITLE
Update Oracle JDK 1.8.0-u131, add JRE and Server JRE.

### PR DESCRIPTION
**Pull request by se35710**

### CODE REVIEW

**Comment by r15ch13** [comment]
Thanks

**Comment by r15ch13** [comment]
Added some improvements with https://github.com/lukesampson/scoop-extras/commit/ba95d6f416fcd819e16dadfb143502f6456547bb :smile:

**Comment by se35710** [comment]
Yeah, I was thinking along the same lines, but got stuck at the version naming. @lukesampson, found another usecase for regex replace with callbacks! :-)

**Comment by lukesampson** [comment]
Noted 😄

**Pull request merged**
