### PR TITLE
Support for STS

### PR DESCRIPTION
**Pull request by javaboy79**
Implemented #554 

A few issues I could not figure out...

1. shortcut path is version dependent, so autoupdate isn't entirely automatic
2. shortcut created should set a target directory to the same dir as the .exe
3. uninstall seems to choke...  I suspect file paths are too long to handle gracefully, as explorer gives this warning also

### CODE REVIEW

**Comment by r15ch13** [comment]
Is the stuff from `pivotal-tc-server-developer-3.2.6.RELEASE` not needed? If so, you could add the `extract_dir` property and set it to `sts-bundle\sts-3.9.0.RELEASE`  (in `autoupdate` set it to `sts-bundle\sts-$version.RELEASE`.

Also here is a improved version regex: 
```regex
spring-tool-suite-(?<version>[\d.]+).RELEASE-e(?<eclipse>(?<short>[\d.]+).[\d]+)-win32.zip
```

Result:
```
$version = 3.9.0
$matchEclipse = 4.7.0
$matchShort = 4.7
```

**Comment by javaboy79** [comment]
@r15ch13  Good eye on the sha1, I didn't notice that.  This is fixed.

I plugged in your regex and it did not work exactly.  I could not see where you were going with that...  Wouldn't adding more matchers to the path be more error prone long term, requiring the script to be updated even if the url format changes slightly?  Especially when we don't really need those bits parsed?  I left the regex as is for now.

Also, I did not see a `formatjson.ps1` script in the bin dir.  It does seem to pass build now though.

As for setting the extract_dir..  Yes, as far as I know `pivotal-tc-server-developer-3.2.6.RELEASE` is required.  It is referenced from STS and I think without it STS is slightly crippled.  The whole bundle is what makes STS, well, STS.  If you tear it apart, you just end up with Eclipse + Spring plugin.  So I do not think extract_dir should be set.

Any comment on how to give the created shortcut a target directory?  Or the uninstall problem I mentioned?

**Comment by rasa** [comment]
@javaboy79: @r15ch13 is referring to https://github.com/lukesampson/scoop/blob/master/bin/formatjson.ps1

**Comment by r15ch13** [comment]
* Most download URLs are stable. IMHO if something changes it's better to take a look at it.
* The shortcut WorkingDirectory setting was discussed before (currently it's not supported)
   https://github.com/lukesampson/scoop/pull/1319
   https://github.com/lukesampson/scoop/pull/1320

* This fixes the long path problem and removes the version from the shortcut path:
  ```json
    "extract_dir": "sts-bundle",
    "pre_install": "mv \"$dir\\sts-$version.RELEASE\" \"$dir\\sts\"",
    "shortcuts": [
        [
            "sts\\STS.exe",
            "Spring Tool Suite"
        ]
    ],
   ```

**Comment by javaboy79** [comment]
@r15ch13 I have incorporated all the recommend changes and also add a `bin` value.  Please review.

**Pull request merged**
