### PR TITLE
marktext: Add bin

### LINKED ISSUE #2825: marktext doesn't create shims
However the app seems to run fine.

```
Installing 'marktext' (0.15.0) [64bit]
marktext-setup-0.15.0.exe (116,9 MB) [====================================================================] 100%
Checking hash of marktext-setup-0.15.0.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
Linking ~\scoop\apps\marktext\current => ~\scoop\apps\marktext\0.15.0
Creating shortcut for Mark Text (Mark Text.exe)
'marktext' (0.15.0) was installed successfully!
```

### PR DESCRIPTION
**Pull request by niheaven**
Fix #2825 

```
Usage: marktext [commands] [path ...]

  Available commands:

        --debug                   Enable debug mode
        --safe                    Disable plugins and other user configuration
        --dump-keyboard-layout    Dump keyboard information
    -n, --new-window              Open a new window on second-instance
        --user-data-dir           Change the user data directory
        --disable-gpu             Disable GPU hardware acceleration
    -v, --verbose                 Be verbose
        --version                 Print version information
    -h, --help                    Print this help message
```

### CODE REVIEW

**Comment by linsui** [comment]
Can we use the zip binary which is smaller (80M/120M) ?

**Comment by niheaven** [comment]
zip files have no given hashes.

**Comment by linsui** [comment]
There are hashes here https://github.com/marktext/marktext/releases

**Comment by niheaven** [comment]
Wow, yes, I'll change it.

**Pull request merged**
