### PR TITLE
Updated wsl-ssh-pageant version to 20190527.1

### PR DESCRIPTION
**Pull request by jeeger**
Updated wsl-ssh-pageant to newer version.

This has the `-force` option, which comes in handy for autostarting the daemon.

### CODE REVIEW

**Comment by jeeger** [comment]
Ack, feel free to edit the commit message.

**Comment by jeeger** [comment]
Hello! What keeps this from getting merged? I could really use that `--force` option.

**Comment by linsui** [comment]
What's the difference between the two binaries? Would it be better to put the cli into main bucket and live gui here? Then they will get autoupdate.

**Comment by jeeger** [comment]
The GUI can run in the background without keeping a command window open (and supports a tray icon), the command line version can't. Apart from that there's no difference.

Why would splitting them in the main bucket and extra change this?

**Comment by linsui** [comment]
Before https://github.com/lukesampson/scoop/pull/3518 is merged, scoop can only autoupdate the first url. Since they are standalone apps, maybe users want to install only one of them?

**Comment by Ash258** [comment]
Well simple reason why this is not going in is that it is not final release. It is prerelease. If you want it create custom gist with it or push it to versiosn bucket.

**Comment by jeeger** [comment]
Hello!
Ah, thanks for the information.

**Pull request closed without merging**
