### PR TITLE
Remove gvim as it duplicates scoop’s vim. Fixes #786

### LINKED ISSUE #786: vim/gvim confusion on what should be in scoop-extras
Scoop contains scoop/buckets/vim.json which contains a `gvim.exe`. The `scoop-extras` bucket contains `gvim.json` (from a different source). Are these both OK? If so, why? `scoop/buckets/vim.json` could be renamed to `scoop/buckets/vim-win-installer` and `scoop-extras` could be renamed to `vim-ftp.json`.

Additionally, within `scoop-extras/gvim.json` contains a post_install that would create `.vimrc`, it should instead create `_vimrc`.

### PR DESCRIPTION
**Pull request by SimplyKnownAsG**
This addresses #786. The gvim.json appears to be unmaintained and redundant.

### CODE REVIEW

**Comment by SimplyKnownAsG** [comment]
@rasa, is there anything else I need to do? Thanks for changing the title, I didn't know if I should put the ticket number in the commit.

**Comment by rasa** [comment]
@SimplyKnownAsG just be patient. #786 will be closed automatically once this is merged.

**Comment by SimplyKnownAsG** [comment]
ok, no worries. thanks.

**Comment by yesbox** [comment]
There's functionality missing. gvim.json adds the gVim start menu shortcut, vim.json does not.

**Comment by r15ch13** [comment]
@yesbox added the shortcut with https://github.com/lukesampson/scoop/commit/82e28da0b86db008c8703a26f5a961e993ac43ce
@SimplyKnownAsG this PR had a merge conflict, so I removed gvim with https://github.com/lukesampson/scoop-extras/commit/87bc2c5de6bdec0f360ffa2538a0bbd4bb0b0b63
I don't know why I didn't merge it earlier 😞

**Pull request closed without merging**
