### PR TITLE
Add installation manifest for pocketsphinx, sphinxbase and phinxtrain

### PR DESCRIPTION
**Pull request by hanabi1224**
https://cmusphinx.github.io/

### CODE REVIEW

**Comment by Ash258** [comment]
Fixed manifest for sphinxbase

```json
{
    "version": "5prealpha",
    "description": "Basic libraries shared by the CMU Sphinx trainer and all the Sphinx decoders.",
    "homepage": "https://cmusphinx.github.io/",
    "license": {
        "identifier": "Proprietary",
        "url": "https://github.com/cmusphinx/sphinxbase/blob/master/LICENSE"
    },
    "url": "https://downloads.sourceforge.net/project/cmusphinx/sphinxbase/5prealpha/sphinxbase-5prealpha-win32.zip",
    "hash": "sha1:1aba8c1438dfbc1522d9e521240d314e56aeeb4e",
    "architecture": {
        "32bit": {
            "extract_dir": "sphinxbase/bin/Release/Win32"
        },
        "64bit": {
            "extract_dir": "sphinxbase/bin/Release/x64"
        }
    },
    "bin": [
        "sphinx_cepview.exe",
        "sphinx_fe.exe",
        "sphinx_jsgf2fsg.exe",
        "sphinx_lm_convert.exe",
        "sphinx_pitch.exe",
        "sphinx_seg.exe"
    ],
    "checkver": {
        "url": "https://sourceforge.net/projects/cmusphinx/files/sphinxbase/",
        "regex": "<span class=\"name\">([\\w]+)</span>"
    },
    "autoupdate": {
        "url": "https://downloads.sourceforge.net/project/cmusphinx/sphinxbase/$version/sphinxbase-$version-win32.zip"
    }
}
```

**Comment by Ash258** [comment]
Fixed manifest for pocket

```json
{
    "version": "5prealpha",
    "description": "Lightweight speech recognition engine, specifically tuned for handheld and mobile devices.",
    "homepage": "https://cmusphinx.github.io/",
    "license": {
        "identifier": "Proprietary",
        "url": "https://github.com/cmusphinx/pocketsphinx/blob/master/LICENSE"
    },
    "url": "https://downloads.sourceforge.net/project/cmusphinx/pocketsphinx/5prealpha/pocketsphinx-5prealpha-win32.zip",
    "hash": "sha1:5d0e7bf205b843f936c5867c3ebc9772002c27bb",
    "architecture": {
        "64bit": {
            "extract_dir": "pocketsphinx/bin/Release/x64"
        },
        "32bit": {
            "extract_dir": "pocketsphinx/bin/Release/Win32"
        }
    },
    "bin": [
        "pocketsphinx_continuous.exe",
        "pocketsphinx_batch.exe",
        "pocketsphinx_mdef_convert.exe"
    ],
    "checkver": {
        "url": "https://sourceforge.net/projects/cmusphinx/files/pocketsphinx/",
        "regex": "<span class=\"name\">([\\w]+)</span>"
    },
    "autoupdate": {
        "url": "https://downloads.sourceforge.net/project/cmusphinx/pocketsphinx/$version/pocketsphinx-$version-win32.zip"
    }
}
```

**Comment by Ash258** [comment]
Fixed manifest for train

```json
{
    "version": "5prealpha",
    "description": "Open source acoustic model trainer.",
    "homepage": "https://cmusphinx.github.io/",
    "license": {
        "identifier": "Proprietary",
        "url": "https://github.com/cmusphinx/sphinxtrain/blob/master/LICENSE"
    },
    "url": "https://downloads.sourceforge.net/project/cmusphinx/sphinxtrain/5prealpha/sphinxtrain-5prealpha-win32.zip",
    "hash": "sha1:17367448497f62066aee6cae8b4c812123bdb37d",
    "architecture": {
        "64bit": {
            "extract_dir": "sphinxtrain/bin/Release/x64"
        },
        "32bit": {
            "extract_dir": "sphinxtrain/bin/Release/Win32"
        }
    },
    "bin": [
        "agg_seg.exe",
        "bldtree.exe",
        "bw.exe",
        "cp_parm.exe",
        "delint.exe",
        "inc_comp.exe",
        "init_gau.exe",
        "init_mixw.exe",
        "kdtree.exe",
        "kmeans_init.exe",
        "make_quests.exe",
        "map_adapt.exe",
        "mixw_interp.exe",
        "mk_flat.exe",
        "mk_mdef_gen.exe",
        "mk_mllr_class.exe",
        "mk_s2sendump.exe",
        "mk_ts2cb.exe",
        "mllr_solve.exe",
        "mllr_transform.exe",
        "norm.exe",
        "param_cnt.exe",
        "tiestate.exe"
    ],
    "checkver": {
        "url": "https://sourceforge.net/projects/cmusphinx/files/sphinxtrain/",
        "regex": "<span class=\"name\">([\\w]+)</span>"
    },
    "autoupdate": {
        "url": "https://downloads.sourceforge.net/project/cmusphinx/sphinxtrain/$version/sphinxtrain-$version-win32.zip"
    }
}
```

**Comment by Ash258** [comment]
Or even better. Match version from [download page](https://cmusphinx.github.io/wiki/download/) with `>name-([\\w]+)</a>`

**Comment by hanabi1224** [comment]
@Ash258  Thank you so much!  Just tested and pushed your fixes

**Pull request merged**
