### PR TITLE
linqpad: fix file names

### PR DESCRIPTION
**Pull request by Bassetts**
Fixes error `Can't shim 'lprun.exe': File doesn't exist.`

### CODE REVIEW

**Comment by Bassetts** [comment]
@Ash258 requested changes made :)

**Comment by Ash258** [comment]
Is everything working with these changes? I do not have enough time to proper test.

Some nested executable calls could potentially call files with its original name.

**Comment by Bassetts** [comment]
image

Tested after making the requested changes and it works perfectly for me.

**Comment by Ash258** [comment]
And application itself is working? I do not know how linqpad is spawning other executables.

I cannot do some advanced testing right as I am perminted from dotnet installation.

**Comment by Bassetts** [comment]
Application launches and works as expected :)

**Pull request merged**
