### PR TITLE
Add Portacle

### PR DESCRIPTION
**Pull request by Retia-Adolf**
😂

### CODE REVIEW

**Comment by r15ch13** [comment]
Wrong file extension :smile:

**Comment by r15ch13** [comment]
Made some changes:
- version regex has to allow letters because of the hotfix version
- add `#/dl.7z` for automatic extraction

But there is one problem I see with persisting a directory like `all`.
Scoop doesn't overwrite/merge directories on an update. Which means you will always use the old contents. (e.g. `all\ssl\ca-bundle.crt` or `all\dictionaries` will not get updated)

**Comment by rasa** [comment]
Could we persist specific files in `all`?

**Comment by Retia-Adolf** [comment]
Maybe no, ok to fess, I don't know..

**Pull request merged**
