### PR TITLE
fmedia 1.10.1 : add fmedia-gui.exe to bin section

### PR DESCRIPTION
**Pull request by hed0n1st**
allows shim creation

### CODE REVIEW

**Comment by Ash258** [comment]
Why?

**Comment by hed0n1st** [comment]
Launch GUI via terminal... but of course it's a personnal decision and must have approbation. I just wanted this possibility.

**Comment by Ash258** [comment]
`fmedia --gui`

**Comment by hed0n1st** [comment]
Totally missed this option... well, forget it :p
And again edition via github is a big fail. Nevermind. And sorry

**Pull request closed without merging**
