### PR TITLE
Eclipse 2018-09 release

### PR DESCRIPTION
**Pull request by se35710**
Removes the need for a [version converter](https://github.com/se35710/scoop-eclipse/blob/master/versions.txt), since version numbers are now numbers and not names.

### CODE REVIEW

**Comment by se35710** [comment]
2018-09 was released, so I have updated the manifests. including minor filename issue (R is not in the filename anymore), and ran a `checkver -u` before commit and push.

Ready to be merged now.

**Comment by r15ch13** [comment]
Just wanted to ask if `eclipse-automotive` and `eclipse-android` are discontinued?
What is the reason for deleting `checkver` and `autoupdate`?

**Comment by se35710** [comment]
@r15ch13 I think so, they were incubator projects that never became "real" projects.

**Comment by r15ch13** [comment]
Okay 👍

**Pull request merged**
