### PR TITLE
Add android-sdk (need testing)

### PR DESCRIPTION
**Pull request by nueko**

### CODE REVIEW

**Comment by r15ch13** [comment]
Still, needs some shims or has to be added to PATH.

**Comment by nueko** [comment]
yes, it does.

**Comment by edgardmessias** [comment]
Same file? https://github.com/lukesampson/scoop-extras/blob/master/bucket/android-sdk.json

**Comment by rasa** [comment]
Appears to be a duplicate of https://github.com/lukesampson/scoop-extras/blob/master/bucket/android-sdk.json

**Pull request closed without merging**
