### PR TITLE
deltachat: Update to version 1.12.0

### PR DESCRIPTION
**Pull request by kunago**

### CODE REVIEW

**Comment by Ash258** [comment]
What is happening with the versioning in this release?

image

**Comment by kunago** [comment]
It must be a naming problem. I will contact the developers.

**Comment by kunago** [comment]
I was told there is a new DeltaChat version available already. The website link will be fixed, however this new version is going to be published instead. The version 1.12.0 should be up to date.

**Comment by Ash258** [comment]
79c7d7eb3f8be76eada3e518e00579ed55efe8dd

**Pull request closed without merging**
