### PR TITLE
kicad-lite: Add version 5.1.9_1

### PR DESCRIPTION
**Pull request by diggit**
This is my first contribution to scoop so please bear me me :)
checkver update works, install works, no paths are auto configured because lite versions do not carry libraries and user should set paths accordingly.
I can't make scoop print out "notes" after install, not sure why.
Stable and nightly can be installed simultaneously.
Stable conflicts with regular kicad manifest (stable, non lite). Is there some "conflicts" option?

### CODE REVIEW

**Review by Ash258 — CHANGES_REQUESTED** [review]
Remove kicad-nightly from extras

**Comment by diggit** [comment]
> Remove kicad-nightly from extras

`extras` bucket is not right place for `kicad-nightly-lite` or what is the problem?

**Comment by Ash258** [comment]
ScoopInstaller/Versions

**Comment by diggit** [comment]
Sorry, I did not know how to accept changes you requested (all I was after clicking "review changes" were my changes). So committed my fixes and removed nightly by myself. Then realized how It should probably be done and removed my commits by force push, but now I don't know how to accept your changes.

**Comment by diggit** [comment]
I recommitted my changes. Next time I'll do it properly, sorry.

**Pull request merged**
