### PR TITLE
Fix ~195 license tags

### PR DESCRIPTION
**Pull request by linsui**
Accidently force-push before commit ...

### CODE REVIEW

**Comment by linsui** [comment]
I didn't change those `Freeware` without a license. It could be changed to `Non-license` easily. What's you suggestion?

**Comment by rasa** [comment]
I removed “non-licensed” from the docs. Let’s just go with “Unknown” if it appears the app doesn’t have a license.

**Comment by linsui** [comment]
OK, I'll change those freeware to unknown and apply new rule.

**Comment by Luckz** [comment]
> Accidently force-push before commit ...

is that what necessitated the `git reset origin/master --hard`?

**Comment by r15ch13** [comment]
@Luckz no, that is related to https://github.com/lukesampson/scoop-extras/pull/2352
The .reg file where added with the wrong line ending. This PR fixed them.

_Sent from my OnePlus5T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
