### PR TITLE
Add Sql Operations Studio

### PR DESCRIPTION
**Pull request by turnertime**
Adds latest preview version of [SQL Operations Studio](https://docs.microsoft.com/en-us/sql/sql-operations-studio/what-is) ([GitHub Repository](https://github.com/Microsoft/sqlopsstudio/)).

Is there a guide for adding new packages? I searched but couldn't find one. Any feedback would be greatly appreciated.

### CODE REVIEW

**Comment by r15ch13** [comment]
Nice!

Made some changes:
- Add `checkver` property (`autoupdate` can be added later when it's stable)
- Use Github release download link, because Microsoft Link redirects to it anyway
- Adding an alias with the same name for `bin` is unnecessary
- Notify the user about being a preview release

```json
{
    "homepage": "https://docs.microsoft.com/en-us/sql/sql-operations-studio",
    "version": "0.26.7",
    "license": "https://raw.githubusercontent.com/Microsoft/sqltoolsservice/master/license.txt",
    "bin": "bin\\sqlops.cmd",
    "shortcuts": [
        [
            "sqlops.exe",
            "SQL Operations Studio"
        ]
    ],
    "url": "https://github.com/Microsoft/sqlopsstudio/releases/download/0.26.6/sqlops-windows-0.26.7.zip",
    "hash": "0EBA82017C43896AFDE22CDAE7B53EF9ED71EAF79D9FD5C368650EB4D155F3C9",
    "extract_dir": "sqlops-windows",
    "notes": "This is still a public preview version!",
    "checkver": {
        "github": "https://github.com/Microsoft/sqlopsstudio"
    }
}
```

**Comment by turnertime** [comment]
@r15ch13 Thanks for the feedback, addressed your comments. Also, do you think `sqlops` would be a better name? the double 's' in `sqlopsstudio` is a bit awkward to type.

Also, I added an [issue](https://github.com/Microsoft/sqlopsstudio/issues/917) to the [SqlOpsStudio repo](https://github.com/Microsoft/sqlopsstudio) asking for help with the package. If you had any information to add to that I'd really appreciate it.

**Comment by turnertime** [comment]
@r15ch13 Also, I just noticed that I accidentally updated the bin to `bin\\sqlops.exe` instead of `bin\\sqlops.cmd`. Are you able to re-open this pull request or should I submit another one?

**Comment by r15ch13** [comment]
@turnertime oh, didn't see the cmd file and changed it to exe in my post earlier. My bad. 😁
Fixed with https://github.com/lukesampson/scoop-extras/commit/aa41ce4ddbd7a786a221477a0ec9832553197ba4

**Pull request merged**
