### PR TITLE
meinplatz: Add version 5.88

### PR DESCRIPTION
**Pull request by AntonOks**

### CODE REVIEW

**Comment by AntonOks** [comment]
> 
> Fixed manifest

Hi & thanks for looking into this and changing the title.
Am I expected to still do something now (beside waiting ;) )?

**Comment by Ash258** [comment]
What about fixing the file??

image

**Comment by AntonOks** [comment]
> 
> 
> ... What about fixing the file with required changes??
> 
> image

can you pls be more precise WHERE I need to add / change WHAT?

I've just copied an existing JSON file and adopted the "meinplatz" stuff... and the installation and removal were also succesfully tested upfront... nevertheless I see that something seems to be missing:
```
C:\Temp\Git\scoop-extras [add_MeinPlatz ≡]
λ  scoop info meinplatz
Could not find manifest for 'meinplatz'.
​C:\Temp\Git\scoop-extras [add_MeinPlatz ≡]
λ  scoop info vlc
Name: vlc
Description: A free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
Version: 3.0.8
Website: https://www.videolan.org/
License: GPL-2.0-only (https://spdx.org/licenses/GPL-2.0-only.html)
Manifest:
  C:\Users\anton\scoop\buckets\extras\bucket\vlc.json
Installed:
  C:\Users\anton\scoop\apps\vlc\3.0.8
Binaries:
  vlc.exe
```
[here ](https://github.com/lukesampson/scoop/wiki/App-Manifests ) it says only "version" is required, which is in the JSON file / manifest, so I obviously miss something :|

**Comment by AntonOks** [comment]
@Ash258 THANK YOU very much!!!

**Pull request merged**
