### PR TITLE
Add PyPy manifest to extras bucket

### PR DESCRIPTION
**Pull request by jfmherokiller**

### CODE REVIEW

**Comment by r15ch13** [comment]
Wouldn't it better to name it `pypy2.json`? Just in case `pypy3` for windows gets released. Also the zip file itself is called `pypy2` :smile:

Can you add the `hash` property to extract the checksum from the download page?
```json
    "autoupdate": {
        "url": "https://bitbucket.org/pypy/pypy/downloads/pypy2-v$version-win32.zip",
        "extract_dir": "pypy2-v$version-win32",
        "hash": {
            "url": "https://pypy.org/download.html"
        }
    }
```

**Comment by jfmherokiller** [comment]
yes you are probably right i just thought naming it pypy would follow the convention used for python

**Comment by r15ch13** [comment]
The build-in [regex ](https://github.com/lukesampson/scoop/blob/master/lib/autoupdate.ps1#L58) works fine because they include the checksums as standard `sha256sum` output format. :smile:

**Comment by jfmherokiller** [comment]
Fixed and i just noticed in the commit i did before applying your suggestion i didnt even have the hash object so regardless of if i had the regex correct it would not have been applied.

**Comment by r15ch13** [comment]
The `mode` property can be omitted because it's the default.

**Pull request merged**
