### PR TITLE
freecommander: Persist Settings folder

### PR DESCRIPTION
**Pull request by hpsbranco**

### CODE REVIEW

**Comment by Ash258** [comment]
https://freecommander.com/en/faq-freecommander/#change-settings-location

You need to first set settings folder location inside config file and then you can persist settings folder.
If you set this, you will break setting for all users, since settings will not be copied from AppData to local folder.

**Comment by Ash258** [comment]
> The fcStart.ini file make the FreeCommander portable: the settings are saved in subfolder of the installation folder.
If you already have the fcStart.ini in your target folder, then you should not overwrite the file.

**Comment by Ash258** [comment]
So revert this change and create new manifest `freecommander-portable` with `installer.script` with `New-Item \"$dir\\fcStart.ini\" -Type File | Out-Null`

**Comment by hpsbranco** [comment]
Actually, on a fresh unzipped install, the "FreeCommander Install Folder" is the default option, and it automatically creates the Settings folder if it doesn't exist. That's why we can get away by just creating the junction.

**Pull request closed without merging**
