### PR TITLE
Add Wavebox

### PR DESCRIPTION
**Pull request by Ash258**

### CODE REVIEW

**Comment by Ash258** [comment]
Could I use something like inside manifest?

```json
"autoupdate": {
    "architecture": {
       "64bit": {
           "url": "https://github.com/wavebox/waveboxapp/releases/download/v$version/Install_Wavebox_$($version.Replace('.', '_'))_x64.exe"
        },
        "32bit": {
           "url": "https://github.com/wavebox/waveboxapp/releases/download/v$version/Install_Wavebox_$($version.Replace('.', '_'))_ia32.exe"
        }
    }
}
```

**Comment by rasa** [comment]
@Ash258 Yes, that works fine.

**Comment by Ash258** [comment]
Awesome. 🙂
Everything fixed and ready to merge.

**Comment by r15ch13** [comment]
It uses [Squirrel](https://github.com/Squirrel/Squirrel.Windows) to update itself, so we can download the `nupkg` file directly without extracting the installer. Needs some digging around to find all necessary URLs. 😄

**Pull request merged**
