### PR TITLE
gnucash: Update to 3.8b (fix checkver.regex)

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by Ash258** [comment]
Is it working fine? 3.8 did not ship needed dlls for Windows.

**Comment by rasa** [comment]
> Is it working fine? 3.8 did not ship needed dlls for Windows.

I installed, but didn’t actually run it. Will test it soon...

**Comment by Ash258** [comment]
Maybe they added some special dependency?

image

**Comment by rasa** [comment]
The 3.8b binary is missing lots of .dlls.
`Dependencies -modules gnucash.exe`
reports:
```
[NOT_FOUND] libunistring-2.dll :
[NOT_FOUND] api-ms-win-core-wow64-l1-1-1.dll :
[NOT_FOUND] api-ms-win-core-winrt-string-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-security-chambers-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-shell32-shellcom-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-comm-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-wow64-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-xstate-l2-1-0.dll :
[NOT_FOUND] api-ms-win-core-xstate-l2-1-1.dll :
[NOT_FOUND] api-ms-win-core-psapi-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-psapi-ansi-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-stringansi-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-core-winrt-remote-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-com-suspendresiliency-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-ro-typeresolution-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-ntuser-window-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-ntuser-window-l1-1-3.dll :
[NOT_FOUND] ext-ms-win-ntuser-window-l1-1-4.dll :
[NOT_FOUND] ext-ms-win-ntuser-window-l1-1-1.dll :
[NOT_FOUND] ngcrecovery.dll :
[NOT_FOUND] ext-ms-win-ntuser-window-l1-1-2.dll :
[NOT_FOUND] ext-ms-win-appmodel-deployment-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-appmodel-usercontext-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-ui-viewmanagement-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-appmodel-viewscalefactor-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-shell-knownfolderext-l1-1-0.dll :
[NOT_FOUND] ext-ms-onecore-defaultdiscovery-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-versionansi-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-versionansi-l1-1-1.dll :
[NOT_FOUND] wc_storage.dll :
[NOT_FOUND] BINDFLT.dll :
[NOT_FOUND] ext-ms-win-security-capauthz-ext-l1-1-0.dll :
[NOT_FOUND] wpaxholder.dll :
[NOT_FOUND] ext-ms-win-shell32-shellfolders-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-shell-shell32-l1-2-0.dll :
[NOT_FOUND] ext-ms-win-shell-shlwapi-l1-1-0.dll :
[NOT_FOUND] ext-ms-windowscore-deviceinfo-l1-1-0.dll :
[NOT_FOUND] dmenterprisediagnostics.dll :
[NOT_FOUND] api-ms-win-coreui-secruntime-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-rtcore-minuser-input-l1-1-1.dll :
[NOT_FOUND] ext-ms-win-uiacore-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-dxcore-l1-1-0.dll :
[NOT_FOUND] ext-ms-mf-pal-l2-1-0.dll :
[NOT_FOUND] ext-ms-win-wer-xbox-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-audiocore-pal-l1-2-0.dll :
[NOT_FOUND] ext-ms-win-shell-tabbedtitlebar-l1-1-0.dll :
[NOT_FOUND] ext-ms-onecore-appmodel-emclient-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-rtcore-minuser-private-ext-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-dwmapi-ext-l1-1-0.dll :
[NOT_FOUND] FVESKYBACKUP.dll :
[NOT_FOUND] EFSCORE.dll :
[NOT_FOUND] HvsiFileTrust.dll :
[NOT_FOUND] EMCLIENT.dll :
[NOT_FOUND] ext-ms-onecore-orientation-l1-1-0.dll :
[NOT_FOUND] ext-ms-onecore-shellchromeapi-l1-1-0.dll :
[NOT_FOUND] ext-ms-win-ras-tapi32-l1-1-1.dll :
[NOT_FOUND] ext-ms-win-networking-wlanstorage-l1-1-0.dll :
[NOT_FOUND] WFDSConMgr.dll :
[NOT_FOUND] libstdc++-6.dll :

**Comment by kbytesys** [comment]
If you install the setup file from github, Gnucash will works without any problem or missing dll.

`libunistring.dll.a` is into the lib subfolder.

**Comment by rasa** [comment]
> If you install the setup file from github, Gnucash will works without any problem or missing dll.
> 
> `libunistring.dll.a` is into the lib subfolder.

Then the solution is to install it via the installer., hopefully using the `/S /D=$dir` switches.

**Comment by rasa** [comment]
```
# Installed via scoop:

$ file libstdc++-6,*.dll libunistring-2*.dll
libstdc++-6,1.dll:    PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows
libstdc++-6,2.dll:    PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows
libunistring-2,1.dll: PE32 executable (DLL) (console) Intel 80386, for MS Windows
libunistring-2,2.dll: PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows

$ ls -l libstdc++-6,*.dll libunistring-2*.dll
-rwxr-xr-x 1 ross 197121 1902627 Aug 29 06:35 libstdc++-6,1.dll
-rwxr-xr-x 1 ross 197121 1902627 Aug 29 06:35 libstdc++-6,2.dll
-rwxr-xr-x 1 ross 197121 5387069 Mar 11  2018 libunistring-2,1.dll
-rwxr-xr-x 1 ross 197121 1933667 Jun  4  2018 libunistring-2,2.dll

# Installed via .exe:

$ file libstdc++-6*.dll libunistring-2*.dll
libstdc++-6.dll:    PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows
libunistring-2.dll: PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows

$ ls -l libstdc++-6*.dll libunistring-2*.dll
-rwxr-xr-x 1 ross 197121 1902627 Aug 29 06:35 libstdc++-6.dll
-rwxr-xr-x 1 ross 197121 1933667 Jun  4  2018 libunistring-2.dll
```

**Comment by kbytesys** [comment]
> -rwxr-xr-x 1 ross 197121 1902627 Aug 29 06:35 libstdc++-6,1.dll
> -rwxr-xr-x 1 ross 197121 1902627 Aug 29 06:35 libstdc++-6,2.dll
> -rwxr-xr-x 1 ross 197121 5387069 Mar 11  2018 libunistring-2,1.dll
> -rwxr-xr-x 1 ross 197121 1933667 Jun  4  2018 libunistring-2,2.dll

I don't think that the comma is allowed in windows filenames. I think that there are two versions of those two libraries and the scoop installer is unable to handle them. Maybe the normal installer just overwrites those libraries files in the destination folder, but I don't know how verify this theory.

**Comment by Ash258** [comment]
They are platform specific then. I will see inno installer file later.

**Comment by rasa** [comment]
> I don't think that the comma is allowed in windows filenames.

They are. The listing was run on Windows, via ls.

**Pull request merged**
