### PR TITLE
Add Jetbrains Rider

### PR DESCRIPTION
**Pull request by moosad**
On request  #1434

### CODE REVIEW

**Comment by Ash258** [comment]
There is no 32bit version for rider: https://rider-support.jetbrains.com/hc/en-us/articles/207876035-Rider-system-requirements

> Windows 10, 8.1, 8 or 7. 64-bit distributions only.

**Comment by moosad** [comment]
Fixed architecture

Missing description is funny, because neither idea and pycharm have one. xD

**Comment by r15ch13** [comment]
It's recommended to use the https://github.com/lukesampson/scoop/blob/master/bucket/jetbrains-toolbox.json

**Comment by moosad** [comment]
@r15ch13
Okay, I was wondering if you could close both my PR and the issue then. Thanks!

**Pull request closed without merging**
