### PR TITLE
playnite: Persist additional folders

### LINKED ISSUE #4919: Playnite persist
Please add Themes and Extensions as persisted folders.
Also: 
`C:\Users\<username>\scoop\apps\playnite\current\Backup\exclusionList.json`
`C:\Users\<username>\scoop\apps\playnite\current\Backup\windowPositions.json`

Maybe all files from backup folder ?

### PR DESCRIPTION
**Pull request by Skyline404**
- Closes #4919 

Presist more folders

### CODE REVIEW

**Review by Ash258 — COMMENTED** [review]
Documentaiton or anything, which explains these folders??

**Comment by Skyline404** [comment]
After each playnite update i need to manually copy these folders for properly playnite work

**Comment by Skyline404** [comment]
> 
> 
> Documentaiton or anything, which explains these folders??

Any progress on this ? Because anybody who uses playnite daily should manually copy these folders after update, only if you don't want your extensions be here, your theme come back to default etc

**Comment by Ash258** [comment]
... A

**Pull request closed without merging**
