### PR TITLE
Fix musescore URL

### PR DESCRIPTION
**Pull request by ruifigueira**
Fixes: #1573

### CODE REVIEW

**Comment by Ash258** [comment]
Add `"extract_dir": "MuseScore $majorVersion"` into autoupdate property.

**Comment by Ash258** [comment]
Also fix checkver to match `releases/MuseScore-([\\d\\.])/` from `https://musescore.org/en/download/musescore.msi` to get correct version without manually adding 0.

**Comment by riaanvn** [comment]
Hi ruifigueira

(apologies for the duplicate post, still finding my feet)

Is there a reason why the Version variable was not brought in in line with the URL? e.g. I believe
"version": "3.0"
should be
"version": "3.0.0"

The next version is expected to be 3.0.1

**Comment by shoogle** [comment]
Thanks for updating the script. I just wanted to point out a few consequences of these changes:

1. Renaming `MuseScore3.exe` to `MuseScore.exe` means that it is not possible to run two versions at the same time (see [this](https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/how-can-i-run-multiple-versions-of-a-program/d61d608b-a2c0-4a5e-b47c-a549f329af1d) and this). This is why `MuseScore.exe` is versioned, but if versioning interferes with scoop's functionality then it is of course up to you guys to decide which functionality you wish to prioritise.

2. Checking the version from `https://musescore.org/en/download/musescore.msi` rather than from `https://musescore.org/en/download` will detect a new version before the MuseScore developers are ready to publish it. Usually they wait a few days after uploading the new version to allow people to test it before publishing it in the download page, and if problems are found they will upload a new version to the same URL. I have contacted the MuseScore team to request that they provide a stable API to the current version that exactly matches the version in the URL.

**Comment by r15ch13** [comment]
1. Hm, for Firefox this is true, but other programs like 7-Zip and MuseScore don't care about this. :smile:
image
image



2. 

> if problems are found they will upload a new version to the same URL

If they keep the version (3.0.0) and just update the, then this will break the manifest anyway.

Musescore itself uses this [appcast.xml](https://sparkle.musescore.org/stable/3/win/appcast.xml) to check for a new version including a build number. Using the full version.build would be the best way.

Version 2 used https://update.musescore.org/update_win_stable.xml, so I guess the URL will change for version 4 anyway. 😁

**Comment by r15ch13** [comment]
https://github.com/lukesampson/scoop-extras/commit/a1f1d02141cf350a8dee071449e43b3b9e408caa

**Comment by shoogle** [comment]
Thanks for fixing! Good idea to use the sparkle appcast!

> If they keep the version (3.0.0) and just update the file, then this will break the manifest anyway.

Indeed, but they wouldn't do this after changing the "current stable version is" text on the download page, which is what my regex was originally checking. However, the appcast is a better solution because there is a small possibility that they do a Windows-only release, e.g. to get the existing program working on a new "version" of Windows (Windows 10 is supposed to be the last version of Windows but you know what I mean - after a big update).

> Hm, for Firefox this is true, but other programs like 7-Zip and MuseScore don't care about this.

Interesting. This is probably because MuseScore 3 uses a different version of Qt to MuseScore 2. Probably whoever changed the executable name was going from prior knowledge that names *sometimes* cause conflicts and didn't test it in this specific case, or tested it but decided not to take the risk.

**Comment by shoogle** [comment]
So I spoke to the MuseScore developers again and they gave me some more reasons for versioning the `MuseScore3.exe` executable. These include:

- Conflicts in the Windows Registry
- Easy distinguishability in the Open With list
- To allow MuseScore 2 to remain available in the Windows Store

None of these reasons are relevant to Scoop.

**Pull request merged**
