### PR TITLE
notepad3: Cleanly replace Windows notepad

### PR DESCRIPTION
**Pull request by phgmacedo**
This is how the original installer does it.

The replace-windows-notepad.reg file was not working how I expected.

### CODE REVIEW

**Comment by pedrogarcia** [comment]
I have fixed the error that prevented the commit from passing the checks. I believe that this is a better solution than it currently exists, or at least it was what I requested in #2384 and proposed in #2385.
Instead of creating a new context menu option, the PR uses a Windows feature called [Image File Execution Options](https://blogs.msdn.microsoft.com/junfeng/2004/04/28/image-file-execution-options/) to redirect Notepad.exe into notepad3.exe without touching any system files. 
 @linsui @rasa @Ash258

**Comment by Luckz** [comment]
As long as nobody ever force-executes the .reg upon simple installation, this is indeed a better way to handle the .reg aspect.

**Comment by pedrogarcia** [comment]
> As long as nobody ever force-executes the .reg upon simple installation, this is indeed a better way to handle the .reg aspect.

It requires admin, if that's what you mean.

**Comment by linsui** [comment]
I don't know much about it... Don't forget to update hash in notepad3.json.

**Pull request closed without merging**
