### PR TITLE
kdenlive: Update to version 20.12.0

### PR DESCRIPTION
**Pull request by igitur**

### CODE REVIEW

**Comment by igitur** [comment]
@Ash258 I fixed the autoupdate URL and regex

**Comment by igitur** [comment]
> The SSL connection could not be established, see inner exception.
> At /SCOOP/apps/scoop/current/lib/install.ps1:130 char:9
> +         throw $e
> +         ~~~~~~~~
> + CategoryInfo          : OperationStopped: (:) [], HttpRequestException

Do I need to anything to solve this?

**Comment by rasa** [comment]
https://download.kde.org/stable/kdenlive/20.12/windows/kdenlive-20.12.0_standalone.exe is fine. What is causing this error to be thrown

**Pull request closed without merging**
