### PR TITLE
hddguardian: Add version 0.7.1

### PR DESCRIPTION
**Pull request by digrouz**

### CODE REVIEW

**Comment by Ash258** [comment]
Using snapfiles and codeplex is not really a good idea for wider user base

image

**Comment by digrouz** [comment]
The fact is that the official website is there now :(

**Comment by digrouz** [comment]
are you suggesting to keep this in a private bucket ?

**Comment by Ash258** [comment]
I am only telling that this cannot go into official bucket unless there is safe provider for homepage and storage. What you will do with it is up to you.

**Comment by digrouz** [comment]
understood :)

**Pull request closed without merging**
