### PR TITLE
bandizip: Update download URL

### PR DESCRIPTION
**Pull request by zhangwang97**

### CODE REVIEW

**Comment by Ash258** [comment]
I do not understand.

Why? Link `https://www.bandisoft.com/bandizip/dl.php?portable` is permanent redirect to `https://dl.bandisoft.com/bandizip.std/BANDIZIP-PORTABLE.ZIP`, which contains both 32bit and 64versions.

Both URLs defined in manifest could be downloaded without any issue (https://dl.bandisoft.com/bandizip/BANDIZIP-PORTABLE-GL-64BIT.ZIP, https://dl.bandisoft.com/bandizip/BANDIZIP-PORTABLE-GL-32BIT.ZIP)

**Comment by zhangwang97** [comment]
> I do not understand.
> 
> Why? Link `https://www.bandisoft.com/bandizip/dl.php?portable` is permanent redirect to `https://dl.bandisoft.com/bandizip.std/BANDIZIP-PORTABLE.ZIP`, which contains both 32bit and 64versions.
> 
> Both URLs defined in manifest could be downloaded without any issue (https://dl.bandisoft.com/bandizip/BANDIZIP-PORTABLE-GL-64BIT.ZIP, https://dl.bandisoft.com/bandizip/BANDIZIP-PORTABLE-GL-32BIT.ZIP)

The file I download from URL `https://dl.bandisoft.com/bandizip/BANDIZIP-PORTABLE-GL-64BIT.ZIP` is version 6.26, instead of version 7.03. I notice that 6.26 is the last version of version 6, so I guess the official changed the download address since version 7. 
I found URL `https://www.bandisoft.com/bandizip/dl.php?portable` and it works fine.

**Comment by jku1995** [comment]
I encountered the same problem.​:sweat_smile:​

**Comment by wenmin92** [comment]
Maybe we should use `https://dl.bandisoft.com/bandizip.std/BANDIZIP-PORTABLE.ZIP` instead.
Note: we also have to change the `shortcuts` and `bin`.

**Comment by Ash258** [comment]
@wenmin92 The manifest has to be reworked. I will do it as soon as I have time.

**Pull request closed without merging**
