### PR TITLE
Add smplayer(portable)

### PR DESCRIPTION
**Pull request by wsw0108**

### CODE REVIEW

**Comment by r15ch13** [comment]
Thanks. Are there more files/directories that can be made [persistent](https://github.com/lukesampson/scoop/wiki/Persistent-data)?

**Comment by wsw0108** [comment]
- playlist.ini
- file_settings/
- style.ass (not sure)

**Comment by r15ch13** [comment]
Can you these to the persist property and verify it?
You can install it via `scoop install <path-to-your-fork>\smplayer.json` to use the current manifest.
Uninstalling works normally: `scoop uninstall smplayer`

**Comment by r15ch13** [comment]
Found these
- player_info.ini
- tv.m3u8
- radio.m3u8
- favorites.m3u8
- style.ass

**Comment by wsw0108** [comment]
```PowerShell
~ $ ls ~\.smplayer\
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2016/12/22     19:54                file_settings
-a----        2016/4/16     21:04            272 device_info.ini
-a----        2017/5/23     14:48              8 favorites.m3u8
-a----        2017/5/23     14:48             77 hdpi.ini
-a----        2017/5/23     14:47          64302 player_info.ini
-a----        2017/5/23     14:48           1331 playlist.ini
-a----        2017/5/23     14:48              8 radio.m3u8
-a----        2017/5/23     14:48          15329 smplayer.ini
-a----        2017/3/27     18:04            300 styles.ass
-a----        2017/5/23     14:48              8 tv.m3u8
```

These are settings under %USERPROFILE% of smplayer with installer.
Only *smpalyer.ini* present in portable version.

**Pull request closed without merging**
