### PR TITLE
lightcord: Add version 0.1.5

### PR DESCRIPTION
**Pull request by sitiom**
A simple and customizable Discord client

### CODE REVIEW

**Review by Ash258 — CHANGES_REQUESTED** [review]
`git mv bucket/Lightcord.json bucket/lightcord.json`

**Comment by Ash258** [comment]
Do not waste actions time on PRs which were not reviewed. Test locally before posting PRs

**Comment by sitiom** [comment]
Fixed. Didn't know lowercase was needed.

**Review by Ash258 — APPROVED** [review]

**Pull request merged**
