### PR TITLE
switchhosts: Adopt portable configuration

### PR DESCRIPTION
**Pull request by cuikangyi**

### CODE REVIEW

**Review by Ash258 — CHANGES_REQUESTED** [review]
Change normal switchhosts manifest to portable with automatically migration of files

**Review by Ash258 — CHANGES_REQUESTED** [review]
There is error on clean installation.

A

<details>
<summary>Fixed manifest</summary>

```json
{
    "version": "3.5.6.5551",
    "description": "Hosts management & switching",
    "homepage": "https://oldj.github.io/SwitchHosts/",
    "license": "MIT",
    "url": "https://github.com/oldj/SwitchHosts/releases/download/v3.5.6/SwitchHosts._windows_installer_3.5.6.5551.exe#/dl.7z",
    "hash": "04b6b6e51767610d37f7f9f8f237ed5637fb5d3dc5f6206dbe825d8cd8efb5e3",
    "architecture": {
        "64bit": {
            "pre_install": "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-64.7z\" \"$dir\""
        },
        "32bit": {
            "pre_install": "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-32.7z\" \"$dir\""
        }
    },
    "installer": {
        "script": [
            "Remove-Item \"$dir\\`$*\", \"$dir\\Uninstall*\" -Recurse",
            "if (!(Test-Path \"$persist_dir\\data\") -and (Test-Path \"$env:USERPROFILE\\.SwitchHosts\")) {",
            "    info \"Migrating '$env:USERPROFILE\\.SwitchHosts' to '$persist_dir\\data'\"",
            "    ensure \"$dir\\data\" | Out-Null",
            "    Copy-Item \"$env:USERPROFILE\\.SwitchHosts\\*\" \"$dir\\data\" -Recurse -Force",
            "    Remove-Item \"$env:USERPROFILE\\.SwitchHosts\" -Recurse",
            "}"
        ]
    },
    "shortcuts": [
        [
            "SwitchHosts!.exe",
            "SwitchHosts!"
        ]
    ],
    "persist": "data",
    "checkver": {
        "github": "https://github.com/oldj/SwitchHosts",
        "regex": "windows_installer_([\\d.]+)\\.exe"
    },
    "autoupdate": {
        "url": "https://github.com/oldj/SwitchHosts/releases/download/v$matchHead/SwitchHosts._windows_installer_$version.exe#/dl.7z"
    }
}

```

</details>

**Comment by cuikangyi** [comment]
Thank you for your reply, I have modified it based on your reply

**Comment by cuikangyi** [comment]
close, the switchhosts 4.0 doesn't support portable mode

**Pull request closed without merging**
