### PR TITLE
lite: Add version 1.11

### PR DESCRIPTION
**Pull request by Nirose**
for issue #4494 and adds persistent folders issue stagnant at #4612

Please review. Thanks!

### CODE REVIEW

**Comment by Ash258** [comment]
I am not going to give credits to you for stealed manifest.

**Comment by Nirose** [comment]
i had created the manifest myself in previous commit #5196 which was marked as a duplicate as I forgot to search the issues, only files in the main repo. I only incorporated the registry editor post_install script from vscodium manifest. I thought that's what open-source is for. they're the same registry files being downloaded, if that seems faking to you then oh well.

I didn't do it for credit, I just wanted to support

**Comment by Ash258** [comment]
Open PR with these changes to #5196 author's repository, wait for merge and then it will be reviewed in original PR.

Sidenote: Adding the lite registries into vscode folder is not good idea

**Comment by Nirose** [comment]
> Adding the lite registries into vscode folder is not good idea
It's not in vscode folder. it's in lite folder.

image

**Comment by Ash258** [comment]
Ahh sorry, my bad. I overlooked the rename instead of new file.

Always create separate files. Never depend in one manifest on files from different manifests. They can easily change and if someone change the code ones, it could negatively influence the lite installation

image

**Comment by Nirose** [comment]
the original author #4612 has confirmed he's not working on it. 

https://github.com/lukesampson/scoop-extras/pull/4612#issuecomment-695207628

I've fixed the registry by creating new files in the scripts folder so it doesn't depend on other manifest. may I create a new PR?

Files changed:
https://github.com/Nirose/scoop-extras/blob/lite111/bucket/lite.json
https://github.com/Nirose/scoop-extras/blob/lite111/scripts/lite-install-context.reg
https://github.com/Nirose/scoop-extras/blob/lite111/scripts/lite-uninstall-context.reg

The registry locations can be changed in the manifest to reflect this repo. if it's ever merged.

**Comment by Nirose** [comment]
> Ahh sorry, my bad. I overlooked the rename instead of new file.
> 
> Always create separate files. Never depend in one manifest on files from different manifests. They can easily change and if someone change the code ones, it could negatively influence the lite installation
> 
> image

can I do a new PR?

**Pull request closed without merging**
