### PR TITLE
Add Bazel

### PR DESCRIPTION
**Pull request by masaeedu**

### CODE REVIEW

**Comment by masaeedu** [comment]
ping @r15ch13 😀

**Comment by rasa** [comment]
It's a 64bit executable, but it's not wrapped in an `architecture` tag, so I'm guessing it's gonna be rejected, as the install will fail on 32bit systems.

**Comment by masaeedu** [comment]
@rasa There's no build for x86 that they publish. Is the correct way to do this to make a `architecture` node and then only put x64 in there?

**Comment by r15ch13** [comment]
Sorry for the late reply, could you add hash extraction because they provide `.sha256` files?

```json
"hash": { "url": "$url.sha256" }
```

**Comment by masaeedu** [comment]
@r15ch13 Ok, done.

**Comment by rasa** [comment]
Unless it has the `architecture` tag, 32bit users wont be told it's not available for their system. Instead, the exe will barf the CPU is wrong.

**Pull request merged**
