### PR TITLE
HashCheck: Add version 2.4.0

### PR DESCRIPTION
**Pull request by niheaven**
Close https://github.com/lukesampson/scoop/issues/3038.

Please MERGE AFTER https://github.com/lukesampson/scoop/pull/3411

### CODE REVIEW

**Comment by indrakaw** [comment]
HashCheck required administrator to modify registry for context menu options. Instead having to `sudo` on installation, why don't you do like `VSCodium` done?

https://github.com/lukesampson/scoop-extras/blob/master/bucket/vscodium.json

**Comment by niheaven** [comment]
- Property page is added by register DLL.
- Context menu is the only entrance of HashCheck, no need to ask user run reg or sth. else themselves.
- Why use this app without proper privilege? There are many cli checksum tools...

**Comment by indrakaw** [comment]
I haven't see the executable binnary yet. Would you please add it to `bin` so it available on cmd?

**Comment by niheaven** [comment]
There is no binary for HashCheck, only `Property` page dll. If you prefer cli tools, please consider `dirhash` or `shasum`.

**Pull request merged**
