### PR TITLE
Update irfanview.json

### PR DESCRIPTION
**Pull request by Befod**
persist "Toolbars"

### CODE REVIEW

**Comment by r15ch13** [comment]
Files inside this directory will never get updated, because scoop doesn't support merging the new directory with the current one, yet.
The same goes for https://github.com/lukesampson/scoop-extras/issues/1766

**Comment by rasa** [comment]
@r15ch13 That’s true for current users, but new users will benefit, yes?

**Comment by r15ch13** [comment]
This will be the case on the next update for every user

**Comment by rasa** [comment]
@r15ch13 so you’re advising rejecting this PR as ineffective?

**Comment by r15ch13** [comment]
@rasa yes

**Pull request closed without merging**
