### PR TITLE
rpcview: Add version 0.3.0.67

### PR DESCRIPTION
**Pull request by L4ys**
A free and powerful tool to explore and decompile all RPC functionalities present on a Microsoft system

### CODE REVIEW

**Comment by Ash258** [comment]
Does not make sense to use automatic, latest build of appveryor.

Come back when there will be valid releaes cycle

**Comment by L4ys** [comment]
Appveryor is the only officially release channel provided by RpcView
so does scoop currently not accept these software that released with Appveryor?

**Comment by Ash258** [comment]
- Downloading latest successful build does not make sense.
- There could be dozens of them daily, which will only spam users.
- Appveyor artifacts are purged after some time

**Pull request closed without merging**
