### PR TITLE
DS4 playstation controller for windows

### LINKED ISSUE #1290: Request: DS4Windows
A utility for mapping PS4 controllers and a bunch of settings and whatnot: https://github.com/Jays2Kings/DS4Windows/releases

### PR DESCRIPTION
**Pull request by Nefariis**
Closes #1290

### CODE REVIEW

**Comment by Ash258** [comment]
- Checkver would not work unless homepage is set to github.
    - change to `"checkver"{"github":"https://github.com/Jays2Kings/DS4Windows"}`
- Use "- Closes #1290" in PR description

**Comment by Nefariis** [comment]
Sorry Im still trying to get a handle on this -

I there any reason why you are using -

`"checkver": {"github": "https://github.com/Jays2Kings/DS4Windows"}`

here but here: https://github.com/lukesampson/scoop-extras/pull/1287

you are using -

`"checkver": "github",`

**Comment by Ash258** [comment]
As I said. Unless homepage is set to github repository URL you can use short form string "github".

**Comment by Nefariis** [comment]
ahhhhh i gotcha - makes sense

**Comment by Ash258** [comment]
Change it to fork, should not be hard. Just use `extract_dir` and `architecture`

**Comment by Nefariis** [comment]
@Ash258 - was that comment meant for this PR?

**Comment by Ash258** [comment]
Yeah. Why to use almost 3 years old software, when you can use new one with latest commits few hours ago.

**Comment by r15ch13** [comment]
I would also recommend using the fork.

**Pull request merged**
