### PR TITLE
Add rustup v1.3.0.

### PR DESCRIPTION
**Pull request by matthewjberger**
This pull request adds rustup, which is a toolchain manager for rust and is the preferred method of installation for the Rust programming language.

### CODE REVIEW

**Comment by matthewjberger** [comment]
The line failing the json validation is the 'autoupdate line'.

```json
"autoupdate": "https://win.rustup.rs/?version=$version#/rustup-init.exe",
```

with the error: `rustup.json: Invalid type. Expected Object but got String.`

I'll look into this soon.

**Comment by r15ch13** [comment]
should be 
```json
    "autoupdate": {
        "url": "https://win.rustup.rs/?version=$version#/rustup-init.exe"
    },
```

What about adding it this to the main bucket?

**Comment by matthewjberger** [comment]
Fixed the manifest, thank you!

I'll submit the manifest over at the main bucket right now

**Comment by r15ch13** [comment]
Added with https://github.com/lukesampson/scoop/commit/579bfce4946772048a62fea2847dca14f527d852 to the main bucket

**Pull request closed without merging**
