### PR TITLE
update neovim

### PR DESCRIPTION
**Pull request by r2qokk**
Update ``neovim-qt`` to ``0.2.3``.
I should have ``neovim`` package point to a particular build, but I cannot find it.
Is there any one willing to help?

### CODE REVIEW

**Comment by r2qokk** [comment]
here's the build history on AppVeryor https://ci.appveyor.com/project/neovim/neovim/history
the neovim v0.1.5 release is on commit 5b8255e

**Comment by r2qokk** [comment]
Use this build https://ci.appveyor.com/project/neovim/neovim/build/7921

**Comment by lukesampson** [comment]
Is this ready to merge, or are you still working on it?

**Comment by r2qokk** [comment]
If no one has concerns on the build I pick, it is good to go now.
I have it tested locally.

2016-10-01 17:20 GMT+08:00 Luke Sampson <notifications@github.com>:

**Comment by lukesampson** [comment]
Thanks!

**Pull request merged**
