### PR TITLE
calibre: Add more bins and shorcuts

### LINKED ISSUE #3278: Is it possible to add a shim to ebook-convert for app "calibre-normal"？
I want to use ebook-convert.exe but it does not in the shims folder hence I need to add the app location to path manually, but that‘s awful.  I tried to find a way to create a shim manually but failed.

### PR DESCRIPTION
**Pull request by niheaven**
Close #3278

### CODE REVIEW

**Comment by linsui** [comment]
ebook-edit, ebook-viewer and lrfviewer have no cli, should we add them into bin? Why not add calibre-customize, calibre-debug, calibre-server and calibre-smtp?

**Comment by niheaven** [comment]
`calibre-*`s got some errors when called from CLI, and may not be run from CLI.

`ebook-edit`, `ebook-viewer` and `lrfviewer` can be run with file name from CLI.

**Comment by linsui** [comment]
They work for me. For example

```
.\calibre-customize.exe -h
用法: calibre-customize.exe options

通过加载外部插件自定义 calibre。


每当向具有它们自己空间的calibre-customize.exe传递参数时，用引号括起这些参数。
例如: "C:\some path with spaces"

  --version             显示程序版本号并退出

  -h, --help            显示此帮助信息并退出

  -a ADD_PLUGIN, --add-plugin=ADD_PLUGIN
                        通过指定包含 ZIP 文件的路径来添加插件。

  -b BUILD_PLUGIN, --build-plugin=BUILD_PLUGIN
                        致插件开发者：指向你所开发插件目录的路径。此命令会自动
压缩插件(zip up)并在 calibre
                        中更新它。

  -r REMOVE_PLUGIN, --remove-plugin=REMOVE_PLUGIN
                        按名称移除自定义插件(对内置插件无效)。

  -h, --help            显示此帮助信息并退出

  -a ADD_PLUGIN, --add-plugin=ADD_PLUGIN
                        通过指定包含 ZIP 文件的路径来添加插件。

  -b BUILD_PLUGIN, --build-plugin=BUILD_PLUGIN
                        致插件开发者：指向你所开发插件目录的路径。此命令会自动
压缩插件(zip up)并在 calibre
                        中更新它。

  -r REMOVE_PLUGIN, --remove-plugin=REMOVE_PLUGIN
                        按名称移除自定义插件(对内置插件无效)。

  --customize-plugin=CUSTOMIZE_PLUGIN
                        自定义插件，使用逗号分隔指定插件名和自定义字串。

  -l, --list-plugins    列出全部已安装的插件

  --enable-plugin=ENABLE_PLUGIN
                        启用该名称插件

  --disable-plugin=DISABLE_PLUGIN
                        禁用该名称插件


作者 Kovid Goyal <kovid@kovidgoyal.net>
```

**Comment by niheaven** [comment]
I don't think they are usefull, what will you do with these `calibre-*`? But okay, added them all.

**Comment by Ash258** [comment]
@niheaven Sync with master

**Comment by niheaven** [comment]
Calibre doesn't update yet, why sync with master?

**Comment by Ash258** [comment]
Because changes here showed version bump to 4.5.0 even when master have same version

**Comment by niheaven** [comment]
Oh, I made this PR when Calibre is 4.4.0.

**Comment by joyinsky** [comment]
Since this version I can't open `calibre` from the command line but I can open `calibre-debug -g`

I get no error. Simply it doesn't open.

**Comment by joyinsky** [comment]
Calibre is trying to open `..\apps\calibre\current\Calibre Portable\calibre-portable.exe`

should open "..\apps\calibre\current\Calibre Portable\Calibre\calibre.exe"

**Pull request merged**
