### PR TITLE
deepgit: Removing 32bit architecture

### PR DESCRIPTION
**Pull request by AntonOks**
Î»  scoop install deepgit
Installing 'deepgit' (4.0.2) [32bit]
deepgit-portable-4_0_2.7z (19,1 MB) [===============================================================================================================] 100%
Checking hash of deepgit-portable-4_0_2.7z ... ok.
Extracting deepgit-portable-4_0_2.7z ... done.
Linking ~\scoop\apps\deepgit\current => ~\scoop\apps\deepgit\4.0.2
Creating shim for 'deepgit'.
Can't shim 'bin\deepgitc32.exe': File doesn't exist.

### CODE REVIEW

**Review by Ash258 — CHANGES_REQUESTED** [review]
- Autoupdate not adjusted
- Where is stated that the developers removed the 32bit version?

**Comment by rasa** [comment]
> * Where is stated that the developers removed the 32bit version?

The [changelog](https://www.syntevo.com/deepgit/changelog.txt) is silent. The only indication is the [download page](https://www.syntevo.com/deepgit/download/) says it's 64bit. The previous [downloads page](https://www.syntevo.com/deepgit/download/archive/) doesn't make that distinction.

**Comment by AntonOks** [comment]
> > * Where is stated that the developers removed the 32bit version?
> 
> The [changelog](https://www.syntevo.com/deepgit/changelog.txt) is silent. The only indication is the [download page](https://www.syntevo.com/deepgit/download/) says it's 64bit. The previous [downloads page](https://www.syntevo.com/deepgit/download/archive/) doesn't make that distinction.

I tried the offered installer on my Miix630 and it says this architecture is not supported but only 64bit....

**Comment by AntonOks** [comment]
>     * Where is stated that the developers removed the 32bit version?

The scoop package aka manifest doesn't work on 32bit architectures anyhow!  Neither does the offered original installer, see my comment below. That's how/why I stumbled over it...

You can now decide to keep this broken manifest as it is and piss 32bit users off (they will **_blame scoop_** not the original SW / installer!) or fix it in a "works as designed" scoop way of things... letting the user know there is no 32bit support for this SW anymore.

**Review by rasa — APPROVED** [review]

**Comment by AntonOks** [comment]
@rasa Thanks for the approval!

**Comment by AntonOks** [comment]
@rasa @ash258 So how will this continue? CAn someone merge it? Or is there anything else required / expected?

**Comment by AntonOks** [comment]
@rasa @Ash258 Things are not getting better... also the just released v4.1 has once again no 32bit binaries

**Pull request merged**
