### PR TITLE
Inkscape: Update to 1.0

### LINKED ISSUE #3988: [Request] update inkscape to v1.0
Is it possible to add it?

https://inkscape.org/release/inkscape-1.0/

### PR DESCRIPTION
**Pull request by ctyytc**
Inkscape: Update to 1.0

Closes #3988

### CODE REVIEW

**Comment by r15ch13** [comment]
This requires some more changes. Can't download it right (the download server seems to be overrun) to check if there is something else that changed.

```json
{
    "version": "1.0",
    "description": "Professional vector graphics editor",
    "homepage": "https://inkscape.org",
    "license": "GPL-3.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://media.inkscape.org/dl/resources/file/inkscape-1.0-x64.7z",
            "hash": "38616b1c5c85a22e1190580b18021ceeade452447d7cd90cbbfcb0c031109dad"
        },
        "32bit": {
            "url": "https://media.inkscape.org/dl/resources/file/inkscape-1.0-x86.7z",
            "hash": "6835afe540ec4ab99b9b471f28682a6f27ad30a77cac783968acdb639b1bad4f"
        }
    },
    "extract_dir": "inkscape",
    "bin": [
        "inkscape.com",
        "inkview.com"
    ],
    "shortcuts": [
        [
            "inkscape.exe",
            "Inkscape"
        ]
    ],
    "checkver": {
        "url": "https://inkscape.org/release/all/windows/64-bit/compressed-7z/",
        "regex": "inkscape-([\\d.]+)-x64.7z",
        "reverse": true
    },
    "autoupdate": {
        "architecture": {
            "32bit": {
                "url": "https://media.inkscape.org/dl/resources/file/inkscape-$version-x86.7z"
            },
            "64bit": {
                "url": "https://media.inkscape.org/dl/resources/file/inkscape-$version-x64.7z"
            }
        },
        "hash": {
            "url": "https://media.inkscape.org/media/resources/sigs/$basename.sha256"
        }
    }
}
```

**Comment by Ash258** [comment]
The server is down for about 6 hours.

**Comment by ctyytc** [comment]
The download URL work for me, looks every thing OK now.

**Comment by Ash258** [comment]
The download is not possible from Czech, Switzerland, Romania and Canada for me.

Cannot test more right now.

**Comment by ctyytc** [comment]
I have tried many times, including using VPN to try multi-country lines, and the download can be completed normally. Can it be merged?

**Comment by r15ch13** [comment]
Please apply the changes from above.

**Pull request closed without merging**
