### PR TITLE
add cmdow & optimize keepass

### PR DESCRIPTION
**Pull request by winteryoung**

### CODE REVIEW

**Comment by rasa** [comment]
This is a better job than
https://github.com/rasa/scoops/blob/master/cmdow.json

**Comment by r15ch13** [comment]
Hm, you accidentally pushed win32-openssh to this PR

**Comment by r15ch13** [comment]
And now keepass. Change your branch 😁

**Comment by winteryoung** [comment]
Well, it's done. Let's accept them all :-)

**Comment by winteryoung** [comment]
they all have been tested

**Comment by r15ch13** [comment]
win32-openssh should go to the main bucket. the other two are okay

**Comment by winteryoung** [comment]
OK, I will move win32-openssh to the main bucket.

**Comment by winteryoung** [comment]
win32-openssh moved.

**Pull request merged**
