### PR TITLE
Pietty: Add version 0.4.00b14

### PR DESCRIPTION
**Pull request by issaclin32**
Please let me know if there are any problems. Thanks.

### CODE REVIEW

**Comment by issaclin32** [comment]
I couldn't find any English (detailed description or user's manual). Therefore I will take down "pcman-lite" and "pcman-combo". Thank you for your help!

**Comment by Ash258** [comment]
Again i cannot recommend to add this into official bucket since hash of downloaded file is different than on page.

image


<details>
<summary>Fixed manifest for pietty</summary>

```json
{
    "version": "0.4.00b14",
    "description": "SSH client based on PuTTY and dedicated to multilingual (especially CJK) environments, accessibility, and simpler user interface.",
    "homepage": "https://sites.google.com/view/pietty-project",
    "license": {
        "identifier": "Freeware",
        "url": "https://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html"
    },
    "url": "https://123.briian.com/forum.php?mod=attachment&aid=NTQyMnw2MDY2ZjIwMXwxNTYwNDIxNjU5fDB8MzIyOQ%3D%3D#/pietty.zip",
    "hash": "badb573f080f17dba3ce6f6cbdc7d2db05284012b0bb09cd34be71fff732a153",
    "bin": [
        [
            "pietty0400b14.exe",
            "pietty"
        ]
    ],
    "shortcuts": [
        [
            "pietty0400b14.exe",
            "PieTTY"
        ]
    ],
    "checkver": {
        "url": "https://sites.google.com/view/pietty-project/download",
        "regex": "PieTTY ([\\w.]+)</a>"
    }
}
```

</details>

**Comment by issaclin32** [comment]
I have modified the download URL, and changed the HASH descriptor from SHA-256 to MD5 (so that the file MD5 is the same as shown on official page)

**Comment by Ash258** [comment]
Ok. Now this url finally return correct file with correct hash.

Attaching fixed manifest with renaming of executable, so future updates do not need to change these properties manually.

<details>
<summary>Fixed manifest</summary>

```json
{
    "version": "0.4.00b14",
    "description": "SSH client based on PuTTY and dedicated to multilingual (especially CJK) environments, accessibility, and simpler user interface.",
    "homepage": "https://sites.google.com/view/pietty-project",
    "license": {
        "identifier": "Freeware",
        "url": "https://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html"
    },
    "url": "https://docs.google.com/uc?export=download&id=1ySJO2ywT6LoVRV2cb3n7qYcaUGJ7ES4J#/pietty.zip",
    "hash": "md5:f42ecd57e924fd3f39e808fa11f61154",
    "pre_install": "Rename-Item \"$dir\\pietty*.exe\" 'pietty.exe'",
    "bin": "pietty.exe",
    "shortcuts": [
        [
            "pietty.exe",
            "PieTTY"
        ]
    ],
    "checkver": {
        "url": "https://sites.google.com/view/pietty-project/download",
        "regex": "PieTTY ([\\w.]+)</a>"
    }
}
```

</details>

**Comment by Ash258** [comment]
One last change.
Fontreg is command line utility. These manifests which provide only cmds are located in Main bucket. 

Remove fontreg from this PR and open new PR with that manifest to https://github.com/ScoopInstaller/Main/ repository

**Comment by issaclin32** [comment]
Thank you so much for your help.
If the Google file ID does expire in the future, I will try to email the author for a more stable URL.

**Comment by rasa** [comment]
This PR is not Pietty any more due to a force push: https://github.com/lukesampson/scoop-extras/compare/5302298c1e88c8e84ad5c01ee959b2862968df6b..be4152f7eaf7a6183e2026c98c13f2e9a71eb2d3

**Comment by issaclin32** [comment]
> This PR is not Pietty any more due to a force push: https://github.com/lukesampson/scoop-extras/compare/5302298c1e88c8e84ad5c01ee959b2862968df6b..be4152f7eaf7a6183e2026c98c13f2e9a71eb2d3

Thanks for noticing. I will reopen the PR.

**Pull request closed without merging**
