### PR TITLE
Supports google-java-format

### PR DESCRIPTION
**Pull request by winteryoung**
The official google-java-format comes only with a jar, without any executables. I wrote another separate launcher for the jar, which barely needs changes in the future. Both are included in this PR.

### CODE REVIEW

**Comment by r15ch13** [comment]
With https://github.com/lukesampson/scoop-extras/pull/545/commits/588f65159690d4d927e4e86ffb5267a72fc3afe1 it now creates a batch file for google-java-format using a `pre_install` script.
Renaming the file is handled by the URL suffix `#/google-java-format.jar`

I recommend that you create a new branch for each pull-request. You don't have to merge the `upstream/master` into your PR. Github handles the merging 😄

**Comment by winteryoung** [comment]
Oh, that's neat. Sorry about the branch. I always forget that.

**Comment by r15ch13** [comment]
Try [GitKraken](https://www.gitkraken.com/) (also [available ](https://github.com/lukesampson/scoop-extras/blob/master/gitkraken.json) with scoop 😁) it's a really nice git GUI 👍

**Comment by winteryoung** [comment]
Thanks, I use command line, barely use GUI. I just tried install google-java-format. It reports error:
```
URL https://github.com/google/google-java-format/releases/download/google-java-format-1.4/google-java-format-1.4-all-deps.jar#/google-java-format.jar is not valid
```

**Comment by r15ch13** [comment]
No other error message?

**Comment by winteryoung** [comment]
No, no other message. Can you install it successfully?

**Comment by winteryoung** [comment]
False alarm. It's my network. Use proxy, and everything goes fine. Sorry.

**Comment by r15ch13** [comment]
Ah okay 👍

**Pull request merged**
