### PR TITLE
cheat-engine: fix checkver

### PR DESCRIPTION
**Pull request by linsui**
It seem the binary is updated twice one day.
close https://github.com/lukesampson/scoop-extras/issues/2813

### CODE REVIEW

**Comment by rasa** [comment]
IMO, anything that updates daily, or especially more often, should live in the (currently unused) [nightlies](https://github.com/ScoopInstaller/Nightlies) bucket. I would think the following would be candidates to move there:

#### Main bucket:
1. [docker-nightly](https://github.com/ScoopInstaller/Main/search?q=docker-nightly&type=Commits)
1. [glslang-nightly](https://github.com/ScoopInstaller/Main/search?q=glslang-nightly&type=Commits)
1. [jar2app](https://github.com/ScoopInstaller/Main/search?q=jar2app&type=Commits)
1. [jx](https://github.com/ScoopInstaller/Main/search?q=jx&type=Commits)
1. [ffmpeg-nightly](https://github.com/ScoopInstaller/Main/search?q=ffmpeg-nightly&type=Commits)

#### Extras bucket:
1. [cheat-engine](https://github.com/lukesampson/scoop-extras/search?q=cheat-engine&type=Commits)
1. [firefox-nightly](https://github.com/lukesampson/scoop-extras/search?q=firefox-nightly&type=Commits)
1. [jdownloader](https://github.com/lukesampson/scoop-extras/search?q=jdownloader&type=Commits)
1. [lightshot](https://github.com/lukesampson/scoop-extras/search?q=lightshot&type=Commits)
1. [oneget](https://github.com/lukesampson/scoop-extras/search?q=oneget&type=Commits)
1. [rust-msvc-nightly](https://github.com/lukesampson/scoop-extras/search?q=rust-msvc-nightly&type=Commits)
1. [rust-nightly](https://github.com/lukesampson/scoop-extras/search?q=rust-nightly&type=Commits)
1. [uplay](https://github.com/lukesampson/scoop-extras/search?q=uplay&type=Commits)
1. [vscode-insiders](https://github.com/lukesampson/scoop-extras/search?q=vscode-insiders&type=Commits)
1. [vscode-insiders-portable](https://github.com/lukesampson/scoop-extras/search?q=vscode-insiders-portable&type=Commits)
1. [watchman-nightly](https://github.com/lukesampson/scoop-extras/search?q=watchman-nightly&type=Commits)

**Comment by linsui** [comment]
We need a clear criteria for including apps in official buckets and a function to move and rename apps between official buckets.
firefox-nightly doesn't update daily. Last update is 5 days ago.

**Comment by rasa** [comment]
> We need a clear criteria for including apps in official buckets and a function to move and rename apps between official buckets.

Agreed. Hence my comment.

> firefox-nightly doesn't update daily. Last update is 5 days ago.

Understood, but packages with a version of “nightly”, are nightly packages by definition, even if they update less often then daily.

**Comment by linsui** [comment]
I wonder why nightlies bucket is deprecated... 
Yeah, please merge or close this pr for now. And let's discuss in a new issue.

**Pull request merged**
