### PR TITLE
add SysInternals Handle 4.1

### PR DESCRIPTION
**Pull request by martinlindhe**

### CODE REVIEW

**Comment by r2qokk** [comment]
```powershell
~ $ scoop update; scoop install handle
updating scoop...
updating extras bucket...
scoop was updated successfully!
installing handle (4.1)
downloading https://download.sysinternals.com/files/Handle.zip...The remote name could not be resolved: 'http'
```

**Comment by martinlindhe** [comment]
The error `The remote name could not be resolved: 'http'` looks strange to me, don't know what is causing that.

**Comment by lukesampson** [comment]
Yes that error is strange. `scoop install handle` works fine for me. Are you using the standard Windows console or something else?

Can you run a trace to get more info on what's going wrong? You can do this with `set-psdebug -t 2`. Then run `scoop install handle`. Run `set-psdebug -off` to turn the trace off.

**Comment by r2qokk** [comment]
Very, very long debug message.
Nice job!
These are only part of the log in the very end.
It goes out of my PowerShell terminal range.

```powershell
DEBUG:  191+ function dl_urls($app, $version, $manifest, $architecture, $dir,
$use_cache = $true, $check_hash = $true)  >>>> {
DEBUG:     ! CALL function 'dl_urls'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\install.ps1')
DEBUG:  194+      >>>> $urls = @(url $manifest $architecture)
DEBUG:  194+     $urls = @( >>>> url $manifest $architecture)
DEBUG:   67+ function url($manifest, $arch)  >>>> { arch_specific 'url'
$manifest $arch }
DEBUG:     ! CALL function 'url'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\manifest.ps1')
DEBUG:   67+ function url($manifest, $arch) {  >>>> arch_specific 'url'
$manifest $arch }
DEBUG:   58+ function arch_specific($prop, $manifest, $architecture)  >>>> {
DEBUG:     ! CALL function 'arch_specific'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\manifest.ps1')
DEBUG:   59+     if( >>>> $manifest.architecture) {
DEBUG:   64+     if( >>>> $manifest.$prop) { return $manifest.$prop }
DEBUG:   64+     if($manifest.$prop) { return  >>>> $manifest.$prop }
DEBUG:   65+  >>>> }
DEBUG:   67+ function url($manifest, $arch) { arch_specific 'url' $manifest
$arch  >>>> }
DEBUG:     ! SET $urls = 'https://download.sysinternals.com/files/Handle.zip'.
DEBUG:  197+      >>>> $cookies = $manifest.cookie
DEBUG:     ! SET $cookies = ''.
DEBUG:  199+      >>>> $fname = $null
DEBUG:     ! SET $fname = ''.
DEBUG:  203+      >>>> $extract_dirs = @(extract_dir $manifest $architecture)
DEBUG:  203+     $extract_dirs = @( >>>> extract_dir $manifest $architecture)
DEBUG:   72+ function extract_dir($manifest, $arch)  >>>> { arch_specific
'extract_dir' $manifest $arch}
DEBUG:     ! CALL function 'extract_dir'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\manifest.ps1')
DEBUG:   72+ function extract_dir($manifest, $arch) {  >>>> arch_specific
'extract_dir' $manifest $arch}
DEBUG:   58+ function arch_specific($prop, $manifest, $architecture)  >>>> {
DEBUG:     ! CALL function 'arch_specific'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\manifest.ps1')
DEBUG:   59+     if( >>>> $manifest.architecture) {
DEBUG:   64+     if( >>>> $manifest.$prop) { return $manifest.$prop }
DEBUG:   65+  >>>> }
DEBUG:   72+ function extract_dir($manifest, $arch) { arch_specific
'extract_dir' $manifest $arch >>>> }
DEBUG:     ! SET $extract_dirs = ''.
DEBUG:  204+      >>>> $extract_tos = @(extract_to $manifest $architecture)
DEBUG:  204+     $extract_tos = @( >>>> extract_to $manifest $architecture)
DEBUG:   73+ function extract_to($manifest, $arch)  >>>> { arch_specific
'extract_to' $manifest $arch}
DEBUG:     ! CALL function 'extract_to'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\manifest.ps1')
DEBUG:   73+ function extract_to($manifest, $arch) {  >>>> arch_specific
'extract_to' $manifest $arch}
DEBUG:   58+ function arch_specific($prop, $manifest, $architecture)  >>>> {
DEBUG:     ! CALL function 'arch_specific'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\manifest.ps1')
DEBUG:   59+     if( >>>> $manifest.architecture) {
DEBUG:   64+     if( >>>> $manifest.$prop) { return $manifest.$prop }
DEBUG:   65+  >>>> }
DEBUG:   73+ function extract_to($manifest, $arch) { arch_specific 'extract_to'
 $manifest $arch >>>> }
DEBUG:     ! SET $extract_tos = ''.
DEBUG:  205+      >>>> $extracted = 0;
DEBUG:     ! SET $extracted = '0'.
DEBUG:  207+     foreach($url in  >>>> $urls) {
DEBUG:     ! SET $foreach = 'IEnumerator'.
DEBUG:  207+     foreach( >>>> $url in $urls) {
DEBUG:     ! SET $url = 'https://download.sysinternals.com/files/Handle.zip'.
DEBUG:  208+          >>>> $fname = (split-path $url -leaf).split('?')[0]
DEBUG:     ! SET $fname = 'Handle.zip'.
DEBUG:  210+          >>>> dl_with_cache $app $version $url "$dir\$fname"
$cookies $use_cache
DEBUG:  100+ function dl_with_cache($app, $version, $url, $to, $cookies,
$use_cache = $true)  >>>> {
DEBUG:     ! CALL function 'dl_with_cache'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\install.ps1')
DEBUG:  101+      >>>> $cached = fullpath (cache_path $app $version $url)
DEBUG:   65+ function cache_path($app, $version, $url)  >>>> {
DEBUG:     ! CALL function 'cache_path'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\install.ps1')
DEBUG:   66+      >>>> "$cachedir\$app#$version#$($url -replace '[^\w\.\-]+',
'_')"
DEBUG:   66+     "$cachedir\$app#$version#$( >>>> $url -replace '[^\w\.\-]+',
'_')"
DEBUG:   67+  >>>> }
DEBUG:   63+ function fullpath($path)  >>>> { # should be ~ rooted
DEBUG:     ! CALL function 'fullpath'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:   64+      >>>>
$executionContext.sessionState.path.getUnresolvedProviderPathFromPSPath($path)
DEBUG:   65+  >>>> }
DEBUG:     ! SET $cached =
'C:\Users\zhur\AppData\Local\scoop\cache\handle#4.1#htt...'.
DEBUG:  102+     if( >>>> !$use_cache) { warn "cache is being ignored" }
DEBUG:  104+     if( >>>> !(test-path $cached) -or !$use_cache) {
DEBUG:  105+          >>>> $null = ensure $cachedir
DEBUG:   62+ function ensure($dir)  >>>> { if(!(test-path $dir)) { mkdir $dir >
 $null }; resolve-path $dir }
DEBUG:     ! CALL function 'ensure'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:   62+ function ensure($dir) { if( >>>> !(test-path $dir)) { mkdir $dir >
 $null }; resolve-path $dir }
DEBUG:   62+ function ensure($dir) { if(!(test-path $dir)) { mkdir $dir > $null
 };  >>>> resolve-path $dir }
DEBUG:   62+ function ensure($dir) { if(!(test-path $dir)) { mkdir $dir > $null
 }; resolve-path $dir  >>>> }
DEBUG:  106+          >>>> write-host "downloading $url..." -nonewline
downloading https://download.sysinternals.com/files/Handle.zip...DEBUG:  107+          >>>> do_dl $url "$cached.download" $cookies
DEBUG:  114+ function do_dl($url, $to, $cookies)  >>>> {
DEBUG:     ! CALL function 'do_dl'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\install.ps1')
DEBUG:  116+         if( >>>> [console]::isoutputredirected) {
DEBUG:  120+              >>>> dl_progress $url $to $cookies
DEBUG:  138+ function dl_progress($url, $to, $cookies)  >>>> {
DEBUG:     ! CALL function 'dl_progress'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\install.ps1')
DEBUG:  139+      >>>> $wreq = [net.webrequest]::create($url)
DEBUG:     ! SET $wreq = 'System.Net.HttpWebRequest'.
DEBUG:  140+     if( >>>> $wreq -is [net.httpwebrequest]) {
DEBUG:  141+          >>>> $wreq.useragent = 'Scoop/1.0'
DEBUG:  142+         if( >>>> $cookies) {
DEBUG:  147+      >>>> $wres = $wreq.getresponse()
DEBUG:  123+          >>>> $e = $_.exception
DEBUG:     ! SET $e = 'System.Management.Automation.MethodInvocationException:
Exc...'.
DEBUG:  124+         if( >>>> $e.innerexception) { $e = $e.innerexception }
DEBUG:  124+         if($e.innerexception) {  >>>> $e = $e.innerexception }
DEBUG:     ! SET $e = 'System.Net.WebException: The remote name could not be
resol...'.
DEBUG:  125+          >>>> abort $e.message
DEBUG:   18+ function abort($msg)  >>>> { write-host $msg -f darkred; exit 1 }
DEBUG:     ! CALL function 'abort'  (defined in file
'C:\Users\zhur\AppData\Local\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:   18+ function abort($msg) {  >>>> write-host $msg -f darkred; exit 1 }
The remote name could not be resolved: 'http'
DEBUG:   18+ function abort($msg) { write-host $msg -f darkred;  >>>> exit 1 }
DEBUG:     ! SET $foreach = ''.
DEBUG:   37+  >>>> }
```

**Comment by martinlindhe** [comment]
Looks like there is issues on your end in resolving download.sysinternals.com.
Does "ping download.sysinternals.com" work?

Also, I might be wrong :-)

**Comment by r2qokk** [comment]
Bingo!
It is a timed out.
Is there a hot patch I can try?

**Comment by lukesampson** [comment]
I don't think this is something we can fix, sorry. It sounds more like a problem with your DNS or proxy server, or some other network connectivity problem.

**Comment by r2qokk** [comment]
Okay, I will keep you guys posted when I have the access to other entry point.

**Comment by r2qokk** [comment]
```powershell
~ $ scoop update
updating scoop...
updating extras bucket...
scoop was updated successfully!
~ $ scoop install handle
it looks like a previous installation of handle failed.
run 'scoop uninstall handle' before retrying the install.
~ $ scoop uninstall handle; scoop install handle
uninstalling handle (4.1)
handle was uninstalled
installing handle (4.1)
downloading https://download.sysinternals.com/files/Handle.zip...The remote name could not be resolved: 'http'
~ $ ping download.sysinternals.com

Pinging cs3.wpc.v0cdn.net [68.232.45.201] with 32 bytes of data:
Reply from 68.232.45.201: bytes=32 time=10ms TTL=57
Reply from 68.232.45.201: bytes=32 time=12ms TTL=57
Reply from 68.232.45.201: bytes=32 time=13ms TTL=57
Reply from 68.232.45.201: bytes=32 time=11ms TTL=57

Ping statistics for 68.232.45.201:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 10ms, Maximum = 13ms, Average = 11ms
```

**Comment by lukesampson** [comment]
Scoop is just using the .NET libraries to download `https://download.sysinternals.com/files/Handle.zip` and somehow it looks like this is being translated into a request for an `http` domain. The only thing I can think of is that there's some misconfiguration on your network, maybe in Internet Options or `scoop config proxy` if you're lucky.
 
Do you use a proxy, or have proxy settings defined in scoop, or in Internet Settings in the Control Panel?

Does it happen when you install any other programs with Scoop?

Are you able to download https://download.sysinternals.com/files/Handle.zip in a browser (esp Internet Explorer or Edge)?

If you can't find any configuration setting amiss, you might have to try running a network trace using something like Fiddler2 or Charles Proxy. You might be able to see why the request is being redirected from `download.sysinternals.com` to `http`.

**Comment by r2qokk** [comment]
It works for me now, please see the update message on the top.
Thank you again for the fast response!

**Pull request merged**
