### PR TITLE
Add ArchWSL (Arch Linux on Windows Subsystem for Linux)

### PR DESCRIPTION
**Pull request by kuinaein**

### CODE REVIEW

**Comment by r15ch13** [comment]
`checkver` could be:
```json
   "checkver": {
        "github": "https://github.com/yuk7/ArchWSL"
    }
```
or
```json
   "checkver": {
        "url": "https://api.github.com/repos/yuk7/ArchWSL/releases/latest",
        "jp": "$.tagname"
    }
```

**Comment by kuinaein** [comment]
Thanks for your review.

- Added pre_install to check if WSL is enabled (I don't know the right way to abort installation, so it simply thorws an exception)
- Fixed checkver

**Comment by r15ch13** [comment]
Running `Arch.exe get --lxuid` returns the following on my machine:
```
λ .\Arch.exe get --lxuid
ERROR:[Arch] is not installed.
Run with no arguments to install
```
Setting the registry value will not work.

Throwing an exception is not a good idea, because of the missing exception handling in scoop.
I would recommend wrapping the install script in the condition and skip it.
Or we could invoke `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux` to install it.

**Comment by r15ch13** [comment]
Is it useful to persist the rootfs? Running `Arch.exe clean` or `wslconfig /u Arch` will trash it. Seems to be the default behavior.

Made some changes:
- combined all scripts into installer and uninstaller
- add `is_admin` check (maybe this should be added to manifest schema, since it should be checked before anything else)
- `join-path` is nice, but makes reading PowerShell code without syntax highlighting even harder to read 😁 
```json
{
    "homepage": "https://github.com/yuk7/ArchWSL/",
    "description": "Install ArchLinux as a WSL Instance",
    "notes": "Even when you are logging in as 'root', some operations (like Docker) require Windows administrator privileges",
    "version": "18081100",
    "url": "https://github.com/yuk7/ArchWSL/releases/download/18081100/Arch.zip",
    "hash": "5fe0f07e9b58f0ca87e8cfa9148be056f0b523ebe3ed53a93b695b5900dae432",
    "checkver": {
        "url": "https://api.github.com/repos/yuk7/ArchWSL/releases/latest",
        "jp": "$.tag_name"
    },
    "autoupdate": {
        "url": "https://github.com/yuk7/ArchWSL/releases/download/$version/Arch.zip"
    },
    "bin": "Arch.exe",
    "shortcuts": [
        [
            "Arch.exe",
            "Arch Linux"
        ]
    ],
    "##": "'rootfs' must be a 'real' directory (at least on Windows 10 RS4)",
    "persist": "data",
    "installer": {
        "script": [
            "if(!(is_admin)) { error \"Please run 'sudo scoop install archwsl'\"; return }",
            "if ($null -eq (Get-Command wslconfig -ErrorAction SilentlyContinue)) {",
            "    warn \"WSL appears not to be enabled!\"",
            "    warn \"Run 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux'\"",
            "    warn \"from an elevated PowerShell. Restart your computer when prompted and reinstall Archwsl.\"",
            "} else {",
            "    'x' | & \"$dir\\Arch.exe\"",
            "    $lx_uid = & \"$dir\\Arch.exe\" get --lxuid",
            "    if(!$lx_uid) { error 'ArchWsl is not installed!'; return }",
            "    Set-ItemProperty -Path \"HKCU:Software\\Microsoft\\Windows\\CurrentVersion\\Lxss\\$lx_uid\" -Name BasePath -Value \"$persist_dir\\data\"",
            "    $persist_fs = \"$persist_dir\\data\\rootfs\"",
            "    if (Test-Path $persist_fs) {",
            "        Remove-Item -Recurse -Path \"$dir\\rootfs\"",
            "    } else {",
            "       Move-Item -Path \"$dir\\rootfs\" -Destination $persist_fs",
            "    }",
            "    Remove-Item -Recurse -Path \"$dir\\temp\"",
            "}"
        ]
    },
    "uninstaller": {
        "script": [
            "if(!(is_admin)) { abort \"Please run 'sudo scoop install archwsl'\" }",
            "$lx_uid = & \"$dir\\Arch.exe\" get --lxuid",
            "if(!$lx_uid) { error 'ArchWsl is not registered!'; return }",
            "Set-ItemProperty -Path \"HKCU:Software\\Microsoft\\Windows\\CurrentVersion\\Lxss\\$lx_uid\" -Name BasePath -Value $dir",
            "New-Item -ItemType Directory -Path \"$dir\\rootfs\" | Out-Null",
            "'x' | & \"$dir\\Arch.exe\" clean"
        ]
    }
}
```

**Comment by rasa** [comment]
> add is_admin check (maybe this should be added to manifest schema, since it should be checked before anything else)

Agreed! Maybe:
`"sudo": true`
?

**Comment by r15ch13** [comment]
- creates a small installer script which is executed via `sudo` (sudo doesn't redirect piped input so this script uses `$p.StandardInput.Write('y')` to skip the `Press any key to continue...` prompt)
- without the `rootfs` hack
- `arch clean` works without admin
```json
{
    "homepage": "https://github.com/yuk7/ArchWSL/",
    "description": "Install ArchLinux as a WSL Instance",
    "notes": "Even when you are logging in as 'root', some operations (like Docker) require Windows administrator privileges",
    "version": "18081100",
    "url": "https://github.com/yuk7/ArchWSL/releases/download/18081100/Arch.zip",
    "hash": "5fe0f07e9b58f0ca87e8cfa9148be056f0b523ebe3ed53a93b695b5900dae432",
    "checkver": {
        "url": "https://api.github.com/repos/yuk7/ArchWSL/releases/latest",
        "jp": "$.tag_name"
    },
    "autoupdate": {
        "url": "https://github.com/yuk7/ArchWSL/releases/download/$version/Arch.zip"
    },
    "bin": "Arch.exe",
    "depends": "sudo",
    "shortcuts": [
        [
            "Arch.exe",
            "Arch Linux"
        ]
    ],
    "installer": {
        "script": [
            "if ($null -eq (Get-Command wslconfig -ErrorAction SilentlyContinue)) {",
            "    warn \"WSL appears not to be enabled!\"",
            "    warn \"Run 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux'\"",
            "    warn \"from an elevated PowerShell. Restart your computer when prompted and reinstall Archwsl.\"",
            "} else {",
            "    \"`$si = New-Object System.Diagnostics.ProcessStartInfo '$dir\\Arch.exe' -Property @{ UseShellExecute = `$false; RedirectStandardInput = `$true }\" | Set-Content \"$dir\\install.ps1\"",
            "    \"`$p = [System.Diagnostics.Process]::Start(`$si)\" | Add-Content \"$dir\\install.ps1\"",
            "    \"`$p.StandardInput.Write('y')\" | Add-Content \"$dir\\install.ps1\"",
            "    \"`$p.WaitForExit()\" | Add-Content \"$dir\\install.ps1\"",
            "    sudo \"$dir\\install.ps1\"",
            "}"
        ]
    },
    "uninstaller": {
        "script": [
            "'y' | & \"$dir\\Arch.exe\" clean"
        ]
    }
}
```

**Comment by kuinaein** [comment]
Thanks a lot! I'll improve it later.

> Is it useful to persist the rootfs? 

- Directory `rootfs` contains all data on Arch Linux filesystem. Configuration files, additionally installed Linux apptications and so on can exist.
- If it's not persisted, all data on the Linux will be lost during update because `scoop update` calls `uninstall` and `install`.
- `Arch.exe` is just a launcher ([source](https://github.com/yuk7/wsldl/blob/master/main.cpp)).

> add is_admin check

Admin privileges __not__ required to:

- Install / uninstall WSL 'distributions'
- Most applications like Ansible, python, etc.

Admin privileges required to:

- Turn on / off the 'Windows feature' Windows Subsystem for Linux
- Some operations like `service docker start` (but we can invoke `docker run` without admin)
  (Note: Docker 17.09.0. or before can run on WSL)

**Comment by r15ch13** [comment]
Running `Arch.exe` without admin doesn't work for me.
```
λ .\Arch.exe
Installing...
ERROR:Installation Failed!
HRESULT:0x80070005
Press any key to continue...
```

**Comment by kuinaein** [comment]
@r15ch13
`HRESULT:0x80070005` means `Access Denied` error.
We have to have `Full Control` permissions of the parent folder of `Arch.exe` to install WSL instance. 
(It shouldn't be a problem because scoop is installed in user's own folder. The same is true for Ubuntu as store app.)

Could you please check it?

**Comment by r15ch13** [comment]
Freshly created directory in `%HOME%`
```
C:\Users\r15ch\arch
λ .\Arch.exe
Installing...
ERROR:Installation Failed!
HRESULT:0x80070002
Press any key to continue...
```

**Comment by kuinaein** [comment]
`HRESULT:0x80070002` => File not found

Is `rootfs.tar.gz` in the same directory as `Arch.exe`?

**Comment by r15ch13** [comment]
Yeah, I didn't have user write privileges on my D:\ drive... I don't have scoop installed in `%HOME%` 😁
This makes 2 hours of tinkering worthless ... 😭

**Comment by kuinaein** [comment]
I actually expereienced the same problem caused by directory permissions...
ACL checking is likely neeeded in `install`.

**Comment by kuinaein** [comment]
@r15ch13 Thanks for your big help!

- Added directory permission check
  - Though WSL distributions can be installed with admin and without Full accesss, it might cause other problems. In WSL `root` doesn't always have special privileges (unlike VirtualBox and other virtual envs)
- Persist `rootfs`. (I wish there were better ways..)

**Comment by r15ch13** [comment]
Now I get `HRESULT:0x800703fa` which seems to be a registry problem. Something broke on my machine. Going to reinstall WSL completely 😁

**Comment by r15ch13** [comment]
Works great now!

**Comment by kuinaein** [comment]
@rasa
FYI. 
Manually download WSL distro packages
https://docs.microsoft.com/en-us/windows/wsl/install-manual

**Pull request merged**
