### PR TITLE
Add Mark Text

### PR DESCRIPTION
**Pull request by beatbrot**

### CODE REVIEW

**Comment by Ash258** [comment]
Fixed manifest: 

<details>

```json
{
    "version": "0.14.0",
    "description": "A simple and elegant markdown editor.",
    "homepage": "https://marktext.app/",
    "license": "MIT",
    "url": "https://github.com/marktext/marktext/releases/download/v0.14.0/marktext-0.14.0.exe#/dl.7z",
    "hash": "a9a5024758895fc92a48ed4220091a78475434ff591100d8464ec4a381a07d4c",
    "extract_dir": "\\$PLUGINSDIR",
    "pre_install": "Get-ChildItem \"$dir\" -Exclude 'app-64.7z', 'app-32.7z' | Remove-Item -Force -Recurse",
    "architecture": {
        "64bit": {
            "installer": {
                "script": "Expand-7zipArchive \"$dir\\app-64.7z\" \"$dir\""
            }
        },
        "32bit": {
            "installer": {
                "script": "Expand-7zipArchive \"$dir\\app-32.7z\" \"$dir\""
            }
        }
    },
    "post_install": "Remove-Item \"$dir\\app-64.7z\", \"$dir\\app-32.7z\"",
    "bin": "Mark Text.exe",
    "shortcuts": [
        [
            "Mark Text.exe",
            "Mark Text"
        ]
    ],
    "checkver": {
        "github": "https://github.com/marktext/marktext/"
    },
    "autoupdate": {
        "url": "https://github.com/marktext/marktext/releases/download/v$version/marktext-$version.exe#/dl.7z",
        "hash": {
            "url": "https://github.com/marktext/marktext/releases/tag/v$version",
            "regex": "(?sm)$basename</code></td>\\s+<td><code>$sha256"
        }
    }
}
```

</details>

**Comment by beatbrot** [comment]
@Ash258 

May I ask what your ratinale was behind all of these changes?

**Comment by Ash258** [comment]
Because it is NSIS based installer. When you launch it as you described it then this happen:

1. It is extracted same way as in manifest, but inside Temporary location
    1. You can mention how slow first startup is.
1. It is executed form there
1. When you quit, all temporary files are deleted

Screenshot when executed downloaded file from scoop_cache folder:

A

B

**Comment by beatbrot** [comment]
Damn, what a nice finding! I will apply all your changes regarding that.

I also saw that you added a regex to extract the hash. I kinda disagree with your approach since many releases do not have the table with all the hashes (See v0.13.53, v0.13.50, v0.12.25, etc. [here](https://github.com/marktext/marktext/releases)). 

Imo using the regex is no safe way to find the hash but at best randomly works for the current release. I am open to suggestions tough...

**Comment by Ash258** [comment]
Then change URL to download `setup` and extract hash from `$baseurl/latest.yml` with regex `sha512:\\s+$base64`

Since that setup and normal exe files are almost identical (only normal / current exe contains that wrapper code for extraction and executing) 

![A](https://i.imgur.com/PTxJIEk.png}

**Comment by beatbrot** [comment]
@Ash258 I tried a few different things, but the checksums never match. Maybe you could help me out? :)

**Pull request merged**
