### PR TITLE
sqlitebrowser: Update to 3.11.2

### LINKED ISSUE #1926: sqlitebrowser portableapp is outdated.
The portable version is outdated and haven't update since 2017. Because, it's outdated, I suggest to switch to zip (no installer) version. See: https://sqlitebrowser.org/dl/

image
It works too.

I had to create an issue about this, see: https://github.com/sqlitebrowser/sqlitebrowser/issues/1819
Hopefully they will update it later. If it get no respond, then consider switching.

### PR DESCRIPTION
**Pull request by TheCjw**
Closes #1926

Changes:
- Check update from github.
- Download archive from github releases.
- Add shortcut for `DB Browser for SQLCipher`

### CODE REVIEW

**Comment by Ash258** [comment]
Fixed manifest
```json
{
    "version": "3.11.2",
    "description": "DB Browser for SQLite (DB4S) project.",
    "homepage": "https://github.com/sqlitebrowser/sqlitebrowser",
    "license": "MPL-2.0|GPL-3.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.11.2/DB.Browser.for.SQLite-3.11.2-win64.zip",
            "hash": "c6117e9d75bde6e0a6cbf51ee2356daa0ce41ca2dd3a6f3d1c221a36104531a0"
        },
        "32bit": {
            "url": "https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.11.2/DB.Browser.for.SQLite-3.11.2-win32.zip",
            "hash": "bdfcd05bf1890a3336a1091c6e9740d582167494d0010da061f9effab2243b9e"
        }
    },
    "extract_dir": "DB Browser for SQLite",
    "bin": [
        "DB Browser for SQLite.exe",
        "DB Browser for SQLCipher.exe"
    ],
    "shortcuts": [
        [
            "DB Browser for SQLite.exe",
            "DB Browser for SQLite"
        ],
        [
            "DB Browser for SQLCipher.exe",
            "DB Browser for SQLCipher"
        ]
    ],
    "persist": "Data",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v$version/DB.Browser.for.SQLite-$version-win64.zip"
            },
            "32bit": {
                "url": "https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v$version/DB.Browser.for.SQLite-$version-win32.zip"
            }
        },
        "hash": {
            "url": "https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v$version/",
            "regex": "$basename\\s*<ul>\\s*<li>$sha256"
        }
    }
}
```

**Comment by TheCjw** [comment]
@Ash258 done.

**Comment by TheCjw** [comment]
@Ash258 It's OK to merge?

**Comment by TheCjw** [comment]
@r15ch13 Please merge this pr when you're free, thanks.

**Comment by Ash258** [comment]
Change PR description
```diff
-Solved issue #1926.
+- Closes #1926
```

**Comment by TheCjw** [comment]
@Ash258 Done.

**Comment by indrakaw** [comment]
Thanks.

**Pull request merged**
