### PR TITLE
Update Xdebug for NTS

### PR DESCRIPTION
**Pull request by jkrehm**
Updated to latest and switched autoupdate to reference vc15

### CODE REVIEW

**Comment by jkrehm** [comment]
Thanks for merging! Unfortunately I missed updating the version number. It should be `2.6.0-7.2`.

**Comment by r15ch13** [comment]
Our auto-update service will catch that in 8 minutes. :smile:

**Comment by jkrehm** [comment]
Oh awesome. Huzzah for auto-updates.

**Comment by r15ch13** [comment]
The `checkver` property had to be updated as well. It's fixed now with https://github.com/lukesampson/scoop-extras/commit/2b8f9c3afbccf7a536a73fb7aa8f5d449a044225 :smile:

**Pull request merged**
