### PR TITLE
riot: Update to version 1.1.0

### PR DESCRIPTION
**Pull request by pitrp**

### CODE REVIEW

**Comment by Ash258** [comment]
Change pre_install property into:

```json
        "pre_install": [
            "Expand-7zipArchive \"$dir\\riot-web-*-full.nupkg\" \"$dir\\temp\" -Removal",
            "Copy-Item \"$dir\\temp\\lib\\net45\\*\" \"$dir\" -Recurse -Force",
            "@('temp', 'background.gif', 'RELEASES', 'Update.exe') | ForEach-Object { Remove-Item \"$dir\\$_\" -Recurse }",
            "cmd /c mklink /J \"$env:APPDATA\\riot\" \"$persist_dir\\data\""
        ],
```

**Comment by pitrp** [comment]
Applied.  Also changed Copy-Item to Move-Item in the process to save resources.
Would an --amend commit and repush do, or how do you like the patch applied?

**Comment by Ash258** [comment]
Just normal commit to same branch

**Comment by pitrp** [comment]
Applied. 64Bit variant tested locally and looks good. 32Bit should work, but untested.

**Pull request merged**
