### PR TITLE
mkvtoolnix@41.0.0: Change download URl

### LINKED ISSUE #3323: mkvtoolnix@40.0.0: download via aria2 failed
image

image

### PR DESCRIPTION
**Pull request by xycui**
- Closes #3323 

The previous link is deprecated. I also found a better place for the permanent resource link 
https://mkvtoolnix.download/windows/releases for all platforms, releases & versions. 
New json file is verified. Please see the following attachment.

image

image

### CODE REVIEW

**Comment by xycui** [comment]
@Ash258 would you please give me a instruction on how to clean commit? I have tried squash but seems not working.

**Comment by Ash258** [comment]
- https://lmgtfy.com/?q=how+to+remove+commits+from+github+PR
- https://gist.github.com/jordanbtucker/17b6c3c7cdaca12327d0

**Comment by xycui** [comment]
> * https://lmgtfy.com/?q=how+to+remove+commits+from+github+PR
> * https://gist.github.com/jordanbtucker/17b6c3c7cdaca12327d0

Appreciate & Done.

**Comment by xycui** [comment]
BTW, the previous link is actually not working. @r15ch13 
image

**Pull request merged**
