### PR TITLE
Add Robomongo

### PR DESCRIPTION
**Pull request by cprecioso**

### CODE REVIEW

**Comment by r15ch13** [comment]
Nice, can you add autoupdate information to it? See [Autoupdate](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate)

**Comment by cprecioso** [comment]
I don't think it's possible, each build has a random number at the end of the name.
I.e.: `https://download.robomongo.org/$version/windows/robomongo-$version-windows-x86_64-$random.zip`
E.g.: `https://download.robomongo.org/0.9.0/windows/robomongo-0.9.0-windows-x86_64-0786489.zip`

**Comment by r15ch13** [comment]
You can use capture groups: `robomongo-(?<version>[\d\w.-]+)-windows-x86_64-(?<random>[\d\w]+).zip`
Now you have `$version` and `$matchRandom` available as variables. They work in `url` and `extract_dir`. (e.g. [haxe.json](https://github.com/lukesampson/scoop/blob/master/bucket/haxe.json))

**Comment by cprecioso** [comment]
I got the autoupdate to work, but it is detecting the first link in the page, which is a problem because that one is sometimes behind a paywall.

**Comment by cprecioso** [comment]
Take a look at https://robomongo.org/download

**Comment by r15ch13** [comment]
This one should do it: `list-block--available.*?robomongo-(?<version>[\d\w.-]+)-windows-x86_64-(?<random>[\d\w]+).zip`
https://regex101.com/r/XxYA2N/1

**Comment by cprecioso** [comment]
Done, thanks for the regex!

**Comment by deevus** [comment]
@r15ch13 What a great regex tool! I'll have to bookmark it

**Pull request merged**
