### PR TITLE
storageexplorer: Extract innosetup instead of install

### PR DESCRIPTION
**Pull request by mjcaley**
Updated Storage Explorer to version 1.11.0 along with the file hash.

### CODE REVIEW

**Comment by Ash258** [comment]
There is no new version listed (https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-explorer-relnotes)

Where did you get this information?

**Comment by mjcaley** [comment]
Ya I noticed that too.  Both the GitHub releases (https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.11.0) and properties of the executable show 1.11.0.

I should have also mentioned issue #2875 which shows the hash mismatch.

**Comment by Ash258** [comment]
Then here you have fixed manifest

<details>
<summary>Fixed manifest</summary>

```json
{
    "version": "1.11.0",
    "description": "Easily manage the contents of Azure storage account.",
    "homepage": "https://azure.microsoft.com/en-us/features/storage-explorer/",
    "license": "CC-BY-4.0",
    "url": "https://github.com/microsoft/AzureStorageExplorer/releases/download/v1.11.0/Windows_StorageExplorer.exe",
    "hash": "d22cef7d7f6d4cf0d266b714ea7d5a894063d6d92557827f58c2cca3593f1ff2",
    "innosetup": true,
    "bin": "StorageExplorer.exe",
    "shortcuts": [
        [
            "StorageExplorer.exe",
            "Azure Storage Explorer"
        ]
    ],
    "checkver": {
        "github": "https://github.com/microsoft/AzureStorageExplorer"
    },
    "autoupdate": {
        "url": "https://github.com/microsoft/AzureStorageExplorer/releases/download/v$version/Windows_StorageExplorer.exe"
    }
}

```

</details>

A

**Comment by outforpublic** [comment]
close #3150

**Pull request merged**
