### PR TITLE
elasticsearch: Fix manifest

### LINKED ISSUE #2061: Elasticsearch version out of date
Elasticsearch has updated to version 7.0.0
They also changed their URL pattern to include the OS and architecture.

artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.0-**_windows-x86_64_**.zip instead of artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.3.zip

The URL, hash, version, and pattern should be updated to resolve this issue.

### PR DESCRIPTION
**Pull request by Ash258**
- Closes #2061
- Closes #2051

- Bump to 7.0.0
- Simplify bins
- Remove suggest to JDKs (JDK is bundled)
- Lint `post_install`
- Add description
- Add license

There are lots of binaries. What needs to be added? /cc @carsonhynes 

A

### CODE REVIEW

**Comment by carsonhynes** [comment]
The files you have exposed in the `bin` section of your PR look fine to me.

**Comment by Ash258** [comment]
That are default, which were there before. What about the rest / new one? Will user ever need any of them being exposed? selasticsearch-sql-cli.bat sounds needed, but never used elasticsearch, so cannot really tell.

**Comment by carsonhynes** [comment]
It wouldn't hurt to expose them as shims but for the most part no. I've never needed anything but `elasticsearch.bat` and
`elasticsearch-service.bat`
personally, but I'm not sure what the Scoop paradigm for including shims is.

**Comment by Ash258** [comment]
I would keep it as it.
When someone request them, it could be added anytime. Since i really do not know purpose of them.

**Pull request merged**
