### PR TITLE
fix(v2rayn): Fix hardlink

### PR DESCRIPTION
**Pull request by h404bi**

### CODE REVIEW

**Comment by linsui** [comment]
We can write it as

```
        "foreach ($file in Get-ChildItem \"$(appdir v2ray $global)\\current\\*\" -File -Include '*.exe', '*.dat', 'vpoint*.json') {",
        "    Write-Host \"Creating hardlink for $($file.Name)\"",
        "    New-Item -ItemType HardLink -Path \"$dir\" -Name $file.Name -Target \"$file\" | Out-Null",
        "}"
```

I found when v2ray is running, v2rayN uninstall will fail. I don't know why can't delete a hardlink when the target is running. Is there any solution?

**Comment by rasa** [comment]
@linsui [taskkill](https://github.com/lukesampson/scoop-extras/search?q=taskkill&unscoped_q=taskkill)?

**Comment by h404bi** [comment]
@rasa Can you merge this fix? I'm encountering shims issue when updating this app.

**Comment by rasa** [comment]
@h404bi Sorry, I missed your message

**Pull request merged**
