### PR TITLE
Add potrace (v1.15)

### PR DESCRIPTION
**Pull request by lahcim8**
The manifest includes both 64 and 32 bit version as well as
checkver-autoupdate mechanism.

### CODE REVIEW

**Comment by r15ch13** [comment]
As a CLI tool, it might be better suited for the main bucket. Do you mind adding it there?
Can you change the `checkver` value to `potrace-([\\d.]+).win64.zip` to match the windows version?

**Comment by rasa** [comment]
Shouldn't that be `potrace-([\\d.]+)\\.win64\\.zip`?

**Comment by lahcim8** [comment]
@rasa Yes, I missed that, thanks.
@r15ch13 I edited the commit, and will also PR on main.

Also could you give me advice on what is the right workflow on editing PR based on suggestions? I feel like changing the commit (what I did now) isn't right but adding more to fix small mistakes seems worse.

**Comment by r15ch13** [comment]
@rasa There are many more manifest using only a dot, but technically you're right :smile:
@lahcim8 just make a new commit to your `potrace` branch and push it. It will show up here.

**Comment by lahcim8** [comment]
I felt like that would make the git history a bit ugly, because apart from this edit I also forgot the trailing end of line character, that would make 3 commits for a simple package add...

But now I edited the commit which was already reviewed by you and I don't feel this is quite right either.

**Comment by r15ch13** [comment]
We use "squash and merge" feature of GitHub. The result is only a single commit in Scoops Git history.

**Comment by rasa** [comment]
Added to main bucket

**Pull request closed without merging**
