### PR TITLE
Oracle Java 10

### PR DESCRIPTION
**Pull request by se35710**
Closes #569

### CODE REVIEW

**Comment by deki** [comment]
Great, I was just looking for that. Developers might need to install different JDK version in parallel (especially because JDK10 isn't LTS). How to achieve that?

**Comment by se35710** [comment]
@deki The usual `scoop install oraclejdk@<version>` doesn't work with Oracle Java. Not sure if `scoop reset oraclejdk@<version>` works, but that would only be applicable for installed versions, which you could use manually by changing `JAVA_HOME`.

For other Java releases, including early access, I've set up my own [scoop bucket](https://github.com/se35710/scoop-java). Feel free to use it.

**Comment by r15ch13** [comment]
@se35710 are you going to maintain your Java bucket and should we add it to the [bucket list](https://github.com/lukesampson/scoop/blob/master/buckets.json)?

**Comment by se35710** [comment]
@r15ch13 Sure, it can be added to the bucket list. I've enabled auto-updates for it and will probably add new GA/EA versions as they are released, but I think the Java manifests should remain in the normal default/extra buckets (but maybe only LTS version, eg. 8 and then 11 (or its’ alias 18.9)).

That would render the Oracle manifests in the versions bucket useless (since the downloads would be behind a login page). Not sure what the retention policy for OpenJDK is.

**Comment by r15ch13** [comment]
Replaced by https://github.com/lukesampson/scoop-extras/pull/898

**Pull request closed without merging**
