### PR TITLE
added mqtt-spy

### PR DESCRIPTION
**Pull request by gitolicious**

### CODE REVIEW

**Comment by rasa** [comment]
Change suggests to suggest

**Comment by r15ch13** [comment]
- rename directly after download by appending `#/mqtt-spy.jar` to the URL
- .jar as `bin` because [this change](https://github.com/lukesampson/scoop/commit/b885ecf5ad08fc350fdfee5ed20a868d259d11d0#diff-f0957a994e6c95d903caeb55bf700101) creates shims for jar files
- fix suggest

```json
{
    "version": "1.0.0",
    "homepage": "https://github.com/eclipse/paho.mqtt-spy",
    "license": "edl-v10",
    "url": "https://github.com/eclipse/paho.mqtt-spy/releases/download/1.0.0/mqtt-spy-1.0.0.jar#/mqtt-spy.jar",
    "suggest": {
        "OracleJRE": [
            "oraclejre"
        ]
    },
    "hash": "4333402f4c2e5212361bc83e0801fccda1cc40acd080c64b656f089122cbc2d0",
    "bin": "mqtt-spy.jar",
    "shortcuts": [
        [
            "mqtt-spy.ps1",
            "mqtt-spy"
        ]
    ],
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/eclipse/paho.mqtt-spy/releases/download/$version/mqtt-spy-$version.jar#/mqtt-spy.jar"
    }
}
```

**Comment by r15ch13** [comment]
```json
    "shortcuts": [
        [
          "mqtt-spy.jar",
          "mqtt-spy"
        ]
    ],
```
Shouldn't this be enough to work?

**Comment by gitolicious** [comment]
That would only work if every user had .jar files linked to java by default which we can not guarantee...

**Pull request merged**
