### PR TITLE
Thunderbird portable: Add version 60.8.0

### PR DESCRIPTION
**Pull request by linsui**

### CODE REVIEW

**Comment by niheaven** [comment]
Making current `thunderbird` portable should be better than adding new one.

**Comment by Ash258** [comment]
@niheaven I do not agree. Since it is set by parameter there is possible that thunderbird will start without this parameter (executed from browser for example), which then will use normal profile from appdata

**Comment by Ash258** [comment]
General configuration is done from current folder, where is simple executable without parameter. No one configure this from start menu / shims folder.

**Comment by linsui** [comment]
@niheaven I don't make current thunderbird portable because only the profile can be portable. Thunderbird has a profile manager and the arg just surpass the manager. The standard version can have several profile but portable version can only use one profile.

**Comment by rasa** [comment]
Question for all: should both packages have a note alerting the user to the other package, and the difference between them?

**Comment by linsui** [comment]
Do you mean a note such as `The portable version can only work with one profile. If you want to work with multiple profiles, please use the stantard version.` ?

**Pull request merged**
