### PR TITLE
foldingathome: Add version 7.5.1

### PR DESCRIPTION
**Pull request by pigsflew**
for issue #3694 . Must be installed global (installer requires sudo).

### CODE REVIEW

**Comment by pigsflew** [comment]
It downloads the installer and runs it. It's because installer is set to an empty object, which by default, has `file` property set to the last URL downloaded.

However, I could see wanting to be explicit here, as this might not be a reliable setting.

I'm actually not sure i like how this works to begin with. It requires the UAC, it doesn't uninstall cleanly... I'm going to look at this again but I don't really know what i'm doing and this one's more complex than the others.

**Comment by Ash258** [comment]
Yes I know. But you are not passing any arguments to it. Which most likely will result into installing it into program files or similar junk, which is unacceptable in official bucket

**Comment by pigsflew** [comment]
That's more than fair.

I have no idea what to do about this one; extracting the exe fails (though I can make 7zip do it "sorta" but i don't know what i need to do to make it cleanly set up that way).

They have an [FAHClient only tar.bz2](https://download.foldingathome.org/releases/public/release/fahclient/windows-10-32bit/v7.5/) that i was able to find, but it's also got an error on unpacking, *and* the FAHClient references the other executables that aren't present in this pack.

I can continue to take stabs at this on my own time; in the meantime I'm closing this mr, thanks!

**Comment by Ash258** [comment]
Try to open PR in non-portable bucket with this version of manifest.

**Comment by pigsflew** [comment]
Actually, I want to try to rewrite it to use the build from [PortableApps](https://portableapps.com/apps/utilities/folding-at-home-portable) - added last week, but it might do the trick! I'll update this and resubmit tonight, thanks for your patience!

**Pull request closed without merging**
