### PR TITLE
musescore: Update to version 3.3.3

### LINKED ISSUE #3264: MuseScore 3.3.3 was released 26 Nov 2019
https://musescore.org/en/3.3.3
and
https://musescore.org/en/handbook/developers-handbook/release-notes/release-notes-musescore-3x/release-notes-musescore-333

### PR DESCRIPTION
**Pull request by riaanvn**
- Closes #3264

### CODE REVIEW

**Comment by Ash258** [comment]
You need to change checker property to get latest version, otherwise this change will be reverted by Excavator in next hour.

**Comment by riaanvn** [comment]
Hi @Ash258 
I am not familiar with the package-fix-needed . When I did an update to this file earlier in the year, there was no such requirement. Can you provide more detail or point me in the right direction? I see a number of PRs have this same issue, looking at 
https://github.com/lukesampson/scoop-extras/labels/package-fix-needed

**Comment by Ash258** [comment]
This cannot be merged without addition fix to the package (manifest). It is mainly for me to not get lost inside all PRs so I do not need to go though all of them and check if user did some changes.

As I said in https://github.com/lukesampson/scoop-extras/pull/3266#issuecomment-558643483.

Without that change this PR is irrelevant when merged, because it will be reverted to 3.3.2 again.

**Comment by riaanvn** [comment]
I hope I understand this correctly. I looked for checkver in the jason file and found
"checkver": {
        "url": "https://sparkle.musescore.org/stable/3/win/appcast.xml",

the appcast.xml file has indeed not been updated to 3.3.3 yet. I have asked the developers to update (they delay it a couple of days to prevent impact if any major bugs are discovered in the new version).

**Comment by Ash258** [comment]
Supressed by 3912dce742146aad3bd76eb371ece815784ea54e

Developers updated appcast file and automatic updates were able to detect and process update.

**Pull request closed without merging**
