### PR TITLE
filezilla.json: Updates to version 3.32.0. Switched sources from sourceforge to original sources.

### PR DESCRIPTION
**Pull request by hannesdorn**
Since sourceforge has not been updated to the latest version, I switch to the original download sources from the website.

### CODE REVIEW

**Comment by r15ch13** [comment]
Can you change `dl3.cdn` to `download` so it's not locked to one mirror?

Can you also add the following to `autoupdate`? This allows extracting the `sha512` checksum.
```json
        "hash": {
            "url": "https://filezilla-project.org/download.php?details=$basename",
            "find": "([a-fA-F0-9]{128})"
        },
```

**Comment by hannesdorn** [comment]
I changed the download links and added the hash url for the updates.
I successfully updated my filezilla.

**Comment by r15ch13** [comment]
Thanks 👍
FYI: Creating a branch to make a PR saves you the merge of the master branch 😃👍

**Comment by se35710** [comment]
@r15ch13 Why not use the sha512 file for hashes?

```
        "hash": {
            "url": "https://download.filezilla-project.org/client/FileZilla_$version.sha512"
        }
```

**Comment by r15ch13** [comment]
@se35710 Good point! I didn't see them 😁

**Pull request merged**
