### PR TITLE
windows application driver

### PR DESCRIPTION
**Pull request by Nefariis**

### CODE REVIEW

**Comment by Nefariis** [comment]
Can someone help me with this error? 

I'm fairly new to this and I dont understand the error.

**Comment by Ash258** [comment]
Autoupdate have to be object, not String.

**Comment by Ash258** [comment]
It's only driver, no need for shortcuts (maybe would be good in main bucket)
I think there should be something like:

```json
"pre_install": [
    "Move-Item -Force -Recure \"$dir\\System\\* \"$dir\\Windows Application Driver\"",
    "Get-ChildItem \"$dir\" -Exclude 'System' | Remove-Item -Force -Recurse",
    "Move-Item \"$dir\\Windows Application Driver\", \"$dir\""
]
```

Go with this manifest:

```json
{
    "version": "1.1",
    "description": "Supports Selenium-like UI Test Automation on Windows Applications.",
    "homepage": "https://github.com/Microsoft/WinAppDriver",
    "url": "https://github.com/Microsoft/WinAppDriver/releases/download/v1.1/WindowsApplicationDriver.msi",
    "hash": "e5e0d8f6d763dcd71b59f12235364e7843079507bda2d6d5c3bd8a2eb204e7f1",
    "bin": "Windows Application Driver\\WinAppDriver.exe",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/Microsoft/WinAppDriver/releases/download/v$version/WindowsApplicationDriver.msi"
    }
}
```

**Comment by Nefariis** [comment]
Im closing this pull request and opening a new pull request in the main scoop bucket with the above changes.

**Pull request closed without merging**
