### PR TITLE
add ImgBurn 2.5.8

### PR DESCRIPTION
**Pull request by oltolm**
ImgBurn is a lightweight CD / DVD / HD DVD / Blu-ray burning application.

### CODE REVIEW

**Comment by brandon93s** [comment]
Looks like the file hashes are also available on the download page. Could extract those instead of downloading to compute the hash.

**Comment by r15ch13** [comment]
The official setup contains AdWare or something. (See [Virustotal](https://www.virustotal.com/#/file/d7dea2819edc77bc44db637cd324e61942b54930cb3034f8f1a417b7dd27b514/detection))
All other download mirrors use URLs with time-based tokens.

I recommend https://etcher.io/
Will add it right now.

**Comment by oltolm** [comment]
>The official setup contains AdWare or something. (See Virustotal)

Does it matter? We are not executing the installer, just unpacking it.

**Comment by r15ch13** [comment]
The download will get interrupted by any AV listed it as bad on VirusTotal (I have ESET NOD32 installed)

**Comment by oltolm** [comment]
I don't think that etcher offers the same functionality. It can't burn images to DVD for example. I'm still in favor of adding imgburn. Not everyone runs an AV that will block it.

**Comment by r15ch13** [comment]
Copied the clean setup from the mirrors to my public keybase.  I removed the `checkver` and `autoupdate` properties since ImgBurn doesn't get updates anymore.
Etcher does is for burning images to USB. That's something completely different. My bad 😁

**Comment by oltolm** [comment]
Thank you, please push to https://github.com/lukesampson/scoop-extras.

**Pull request merged**
