### PR TITLE
testcentric: Change download URL to Choco

### PR DESCRIPTION
**Pull request by niheaven**

### CODE REVIEW

**Comment by rasa** [comment]
Github still hosts the .nupkg. Why the switch?

Please note a .zip file is also provided. See https://github.com/TestCentric/testcentric-gui/blob/master/README.md#installation

**Comment by niheaven** [comment]
It is recommanded by author, and switching to Choco will have extracted file hash so as to provide better integrity check.

**Comment by rasa** [comment]
Have we asked the chocolatey admins if we can do this? I wonder if their terms of service allow this use? We are a competitor of sorts, and they offer a paid service.

**Comment by rasa** [comment]
I never heard back from Rob @ Chocolatey.

**Pull request merged**
