### PR TITLE
Add DriverStore Explorer version 0.10.15

### PR DESCRIPTION
**Pull request by DavidSHwang**

### CODE REVIEW

**Comment by r15ch13** [comment]
Please run `.\bin\checkver.ps1 driverstoreexplorer -f` and push the changes. No need to make a new Pull-request.
https://github.com/lukesampson/scoop-extras/pull/2129

**Comment by Ash258** [comment]
There is some pdb file. Should it be persisted?

**Comment by r15ch13** [comment]
@Ash258 pdb files contain .NET debugger stuff and can be ignored

**Comment by DavidSHwang** [comment]
Seems that `Rapr.exe.config` should be persisted. Working on it.

**Comment by Ash258** [comment]
There is usually saved only files which are required to run exe files (dlls, ...)
Is there any special config option, which is related?

**Comment by DavidSHwang** [comment]
The config file memorises the language option and the location of the window. Are these necessary to be kept?

**Comment by r15ch13** [comment]
Nope, that is also a .NET file. It just describes the configuration. The settings will actually be stored in `%appdata%`. Please remove the `persist` property.

**Comment by DavidSHwang** [comment]
Done.

**Pull request merged**
