### PR TITLE
winfetch: Update to version 2.0.0

### PR DESCRIPTION
**Pull request by rashil2000**

### CODE REVIEW

**Comment by jcwillox** [comment]
In the next release of `winfetch` the script will have been renamed from `posh-winfetch.ps1` to `winfetch.ps1`, we are updating the scoop manifest to reflect that.

@rashil2000 you can also remove `#/winfetch.ps1` from `autoupdate`, as we do not need to rename the downloaded file anymore.

**Comment by jcwillox** [comment]
It would be great to get this PR merged as we are unable to release `v2.0.0` of winfetch until then.

**Comment by Ash258** [comment]
This PR will be merged as soon as the version change. So release new version and then it will be updated and merged.

**Comment by jcwillox** [comment]
Well, we took a little longer than expected as we decided to polish up a couple of things before the release, but finally, [v2.0.0](https://github.com/lptstr/winfetch/releases/tag/v2.0.0) has been released.

**Comment by Ash258** [comment]
There were no update by @rashil2000. Merging only this change is not optimal. Update this pr with new version and it will be merged. Spamming users with two commits instead of one in log does not make sense.

**Pull request merged**
