### PR TITLE
add bleachbit

### PR DESCRIPTION
**Pull request by s-i-v-r-a-j**
first app manifest, so please critique and I will make any changes necessary. thanks.

### CODE REVIEW

**Comment by r15ch13** [comment]
Looking good so far. :+1:
Could you add hash extraction by adding the following to the `autoupdate` property?

```json
"hash": {
     "url": "$baseurl/bleachbit-2.0-sha256sum.txt"
}
```

**Comment by s-i-v-r-a-j** [comment]
Sure. but should that include `$version` instead of `2.0`?

```
"hash": {
  "url": "$baseurl/bleachbit-$version-sha256sum.txt"
}
```

**Comment by s-i-v-r-a-j** [comment]
I updated using the hash url of "$baseurl/bleachbit-2.0-sha256sum.txt" because bleachbit appears to update the sha256sum file with the newest version. Let me know if I've made a wrong choice here. thanks

**Comment by s-i-v-r-a-j** [comment]
I updated using the hash url of "$baseurl/bleachbit-$version-sha256sum.txt" because bleachbit appears to update the sha256sum file with the newest version. Let me know if I've made a wrong choice here. thanks

**Pull request merged**
