### PR TITLE
jetbrains toolbox, bandizip install

### PR DESCRIPTION
**Pull request by archmagece**
Metadata for jetbrains-toolbox and bandizip(korean zip software).

In Bandizip, Right click function is not working.
But else works fine.

### CODE REVIEW

**Comment by Ash258** [comment]
Toolbox is already in main bucket.

**Comment by Ash258** [comment]
@r15ch13 You forgot ini file for 32bit version

**Comment by r15ch13** [comment]
@Ash258 Yup missed that :grin:
Persisting files base on architecture is not implemented though ...

**Comment by Ash258** [comment]
But you still need to persist both of them.
Resulted in "Specified file was not found while install"

**Comment by r15ch13** [comment]
Should work now 😁

**Comment by r15ch13** [comment]
@archmagece can add the changes discussed above?

**Comment by archmagece** [comment]
In my PC pre_install script error.
- Win10

Then I changed this line
```
"Rename-Item \"$dir\\Bandizip*.exe\" \"$dir\\Bandizip.exe\""
->
"Get-ChildItem \"$dir\\Bandizip*.exe\" | Rename-Item -NewName \"$dir\\Bandizip.exe\"",
```
It works better for me.

**Pull request merged**
