### PR TITLE
Added SnakeTail v1.9.0

### PR DESCRIPTION
**Pull request by teppos**
Added SnakeTail v1.9.0

### CODE REVIEW

**Comment by rasa** [comment]
Version is 1.9.0, but url and https://github.com/snakefoot/snaketail-net say 1.9.4?

**Comment by teppos** [comment]
Ah I may have made a typo. Should be 1.9.4

**Comment by teppos** [comment]
Kinda a git(hub) newbie still . Do I make a new pull request to fix it?

**Comment by r15ch13** [comment]
Auto update fixed it: https://github.com/lukesampson/scoop-extras/commit/4132f06b34f2e72e8d54ecb4a39743c2d3ac5cb5

**Comment by teppos** [comment]
Good, thanks.

**Comment by rasa** [comment]
I thought it might.

**Pull request merged**
