### PR TITLE
freac@1.1.2: Fix url

### LINKED ISSUE #4517: freac@1.1.2: Download failed
❯ scoop install freac
Installing 'freac' (1.1.2) [64bit]
Servererror: (404) Not found.
URL https://github.com/enzo1982/freac/releases/download/v1.1.2/freac-1.1.2a-windows-x64.zip is not valid

New URL is with 1.1.2b in filename :(

### PR DESCRIPTION
**Pull request by adnaanbheda**
- Closes #4517

### Description
Updates the freac download url

### CODE REVIEW

**Comment by Ash258** [comment]
/verify

No hash changes?...

**Comment by adnaanbheda** [comment]
> /verify
> 
> No hash changes?...

Hey, sorry, I'm new here, how do I check the hash change ?

**Comment by adnaanbheda** [comment]
@Ash258 I've updated the hashes, why isn't the autoupdate working ? I'll try and fix it.

**Comment by Ash258** [comment]
Do not touch the autoupdate

**Pull request merged**
