### PR TITLE
zaproxy: Add version 2.9.0

### PR DESCRIPTION
**Pull request by WataruMatsuoka**

### CODE REVIEW

**Comment by Ash258** [comment]
Why did you take crossplatform binaries over windows specific?

**Comment by WataruMatsuoka** [comment]
@Ash258 I didn't know how to set windows specific binary as a source of package.

**Comment by Ash258** [comment]
Are there any files, which should be persisted?

**Comment by WataruMatsuoka** [comment]
"plugin" folder should.
Could you add "persist" property at proper line?

**Pull request merged**
