### PR TITLE
Add DevDocs at version 0.6.7

### PR DESCRIPTION
**Pull request by brandon93s**

### CODE REVIEW

**Comment by brandon93s** [comment]
@r15ch13 👋

**Comment by r15ch13** [comment]
Too many tickets lately, can't keep up 😁

**Comment by brandon93s** [comment]
Need another merger? I can help handle some of the manifest update & addition reviews.

**Comment by r15ch13** [comment]
@brandon93s that would be a big help. But you have to contact @lukesampson for this.
Your PRs are top quality! ❤️

**Comment by rasa** [comment]
@r15ch13: I'm happy to help too, though I would defer merging any non-manifest related stuff to the experts. Should I ask @lukesampson?

**Comment by r15ch13** [comment]
@rasa 👍

**Pull request merged**
